import assert from "node:assert/strict";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";

const root = process.cwd();
const cli = join(root, "dist", "cli.js");
const lib = join(root, "dist", "nosedive.js");
const { readNosediveRc, writeNosediveRcCurrent } = await import(pathToFileURL(lib).href);
const tmp = mkdtempSync(join(tmpdir(), "nosedive-test-"));
const gitLocalEnvKeys = [
  "GIT_ALTERNATE_OBJECT_DIRECTORIES",
  "GIT_COMMON_DIR",
  "GIT_DIR",
  "GIT_INDEX_FILE",
  "GIT_OBJECT_DIRECTORY",
  "GIT_PREFIX",
  "GIT_WORK_TREE",
];

function write(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf8");
}

function run(args, cwd, input) {
  return spawnSync(process.execPath, [cli, ...args], {
    cwd,
    encoding: "utf8",
    input,
  });
}

function runTool(command, args, cwd) {
  const env = { ...process.env };
  for (const key of gitLocalEnvKeys) delete env[key];
  const result = spawnSync(command, args, { cwd, encoding: "utf8", env });
  assert.equal(result.status, 0, `${command} ${args.join(" ")} failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);
  return result;
}

function assertOk(result, label) {
  assert.equal(result.status, 0, `${label}\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function assertContainsPath(text, path) {
  assert.match(text, new RegExp(escapeRegExp(path)));
}

function assertGeneratedFrontmatter(text, filename, fields = []) {
  const expected = [
    "---",
    `generated-by: "nosedive"`,
    `generated-file: "${filename}"`,
    "do-not-edit: true",
    `gist: "Generated by nosedive from kb; do not edit by hand."`,
    ...fields,
    "---",
    "",
  ].join("\n");
  assert.equal(text.startsWith(expected), true, `expected generated frontmatter:\n${expected}\nactual start:\n${text.slice(0, 300)}`);
}

try {
  const importOnly = spawnSync(process.execPath, ["-e", `import(${JSON.stringify(pathToFileURL(lib).href)})`], {
    cwd: root,
    encoding: "utf8",
  });
  assertOk(importOnly, "library import failed");
  assert.equal(importOnly.stdout, "", "library import unexpectedly wrote to stdout");
  assert.equal(importOnly.stderr, "", "library import unexpectedly wrote to stderr");

  const version = run(["version"], root);
  assertOk(version, "version command failed");
  assert.match(version.stdout.trim(), /^(\d+\.\d+\.\d+(?:-\d+)?|0\.0\.0-dev)$/);

  const help = run(["--help"], root);
  assertOk(help, "--help command failed");
  assert.match(help.stdout, /Usage: nosedive <command>/);
  assert.match(help.stdout, /mint/);
  assert.match(help.stdout, /init/);
  assert.match(help.stdout, /dump-backlog/);
  assert.match(help.stdout, /pitch/);
  assert.match(help.stdout, /add-repo/);

  const minted = run(["mint", "1997-08-29T02:14:00-04:00", "2"], root);
  assertOk(minted, "mint command failed");
  const mintedLines = minted.stdout.trim().split(/\r?\n/);
  assert.equal(mintedLines.length, 2, "mint should print one UUID per line");
  assert.match(mintedLines[0], /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
  assert.match(mintedLines[1], /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
  assert.equal(mintedLines[0] < mintedLines[1], true, "mint count mode should advance timestamps by 1ms and sort lexicographically");

  const mintedNow = run(["mint"], root);
  assertOk(mintedNow, "mint default timestamp command failed");
  assert.match(mintedNow.stdout.trim(), /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);

  const bridge = join(tmp, "bridge");
  mkdirSync(join(bridge, "workspace", "writable", "app"), { recursive: true });
  mkdirSync(join(bridge, "workspace", "readonly", "app"), { recursive: true });
  mkdirSync(join(bridge, "backlog", "yaml-frontmatter"), { recursive: true });
  mkdirSync(join(bridge, "backlog", "other-effort"), { recursive: true });
  mkdirSync(join(bridge, "backlog", "gogglebox", "auth-refactor"), { recursive: true });
  mkdirSync(join(bridge, "backlog", "yaml-frontmatter", ".artifacts"), { recursive: true });
  mkdirSync(join(bridge, "kb"), { recursive: true });

  const writableRoot = join(bridge, "workspace", "writable");
  const readonlyRoot = join(bridge, "workspace", "readonly");
  const bridgeExclude = join(bridge, ".git", "info", "exclude");
  const writableExclude = join(writableRoot, ".git", "info", "exclude");
  const readonlyExclude = join(readonlyRoot, ".git", "info", "exclude");

  runTool("git", ["init"], bridge);
  runTool("git", ["init"], writableRoot);
  runTool("git", ["init"], readonlyRoot);
  write(bridgeExclude, "# user bridge exclude\n*.bridge-local\n");
  write(writableExclude, "# user writable exclude\n*.writable-local\n");
  write(readonlyExclude, "# user readonly exclude\n*.readonly-local\n");
  write(join(writableRoot, "CLAUDE.md"), "# Tracked local instructions\n");
  runTool("git", ["add", "CLAUDE.md"], writableRoot);
  runTool("git", ["-c", "user.name=Nosedive Test", "-c", "user.email=nosedive@example.invalid", "commit", "-m", "Track CLAUDE"], writableRoot);

  write(
    join(bridge, ".nosediverc"),
    `workspace: ./workspace
backlog: ./backlog
kb: ./kb
home-branch: main
work-branch-prefix: work/
custom-scalar: keep-me
current:
  effort: yaml-frontmatter/YamlFrontmatter.md
`,
  );
  write(
    join(bridge, "backlog", "yaml-frontmatter", "YamlFrontmatter.md"),
    `---
phase: building
gist: "Exercise valid YAML: quoted effort gist"
repos:
  - repo-writable
  - repo-readonly@develop:ro
---

# YAML frontmatter

Build the YAML-aware workspace work order.
`,
  );
  write(
    join(bridge, "backlog", "other-effort", "OtherEffort.md"),
    `---
phase: framing
gist: "Another open effort: visible in verbose backlog output."
---

# Other effort
`,
  );
  write(
    join(bridge, "backlog", "gogglebox", "README.md"),
    `# Gogglebox Domain

This markdown file documents the domain and must not make it an effort.
`,
  );
  write(
    join(bridge, "backlog", "gogglebox", "auth-refactor", "AuthRefactor.md"),
    `---
phase: shaping
gist: "Domain-qualified effort under a project namespace."
---

# Auth Refactor
`,
  );
  write(
    join(bridge, "backlog", "yaml-frontmatter", ".artifacts", "proof.md"),
    `# Proof

Artifact markdown must not be discovered as an effort.
`,
  );
  write(
    join(bridge, "kb", "repo-writable.md"),
    `---
kind: repo
id: repo-writable
name: writable
gist: "Writable repo: quoted gist"
meta:
  path: workspace/writable
  base-branch: develop
---
`,
  );
  write(
    join(bridge, "kb", "repo-readonly.md"),
    `---
kind: repo
id: repo-readonly
name: readonly
gist: "Read-only repo: quoted gist"
meta:
  path: workspace/readonly
---
`,
  );
  write(
    join(bridge, "kb", "convention.md"),
    `---
kind: convention
id: convention-doc
name: convention.test
gist: "Quoted gist: colon, \\"quotes\\", and \`backticks\` survive YAML parsing."
scopes:
  - repo-writable
  - repo-readonly/app:gist
---

# Convention body
`,
  );
  write(
    join(bridge, "kb", "assertion.md"),
    `---
kind: assertion
id: assertion-doc
name: assertion.test
gist: "Scoped assertion gists render by default."
scopes:
  - repo-writable@abc123:ro,gist
---

# Assertion body
`,
  );
  write(
    join(bridge, "kb", "old-colon-scope.md"),
    `---
kind: assertion
id: old-colon-scope
name: old-colon-scope.test
gist: "Old multi-colon scopes do not render."
scopes:
  - repo-writable:ro:gist
---

# Old colon scope body
`,
  );
  write(
    join(bridge, "kb", "decision.md"),
    `---
kind: decision
id: decision-doc
name: decision.test
gist: "Scoped decision gists render by default."
scopes:
  - repo-writable
links:
  - foundation-doc#frontmatter
---

# Decision body
`,
  );
  write(
    join(bridge, "kb", "runbook-workon.md"),
    `---
kind: runbook
id: runbook-workon
name: workon
gist: "Start working on an effort."
scopes:
  - .
---

# Workon

Run the workon flow after reading this doc.
`,
  );
  write(
    join(bridge, "kb", "runbook-repo.md"),
    `---
kind: runbook
id: runbook-repo
name: repo-runbook.test
gist: "Repo-scoped runbooks render as gists."
scopes:
  - repo-writable
---

# Repo runbook body
`,
  );
  write(
    join(bridge, "kb", "foundation.md"),
    `---
kind: foundation
id: foundation-doc
name: foundation.test
gist: "Foundation gist: body render uses markdown body."
scopes:
  - repo-writable/app:body
---

# Foundation Body

Body rendered from valid YAML frontmatter.
`,
  );

  const dryRun = run(["apply", "--dry-run"], bridge);
  assertOk(dryRun, "apply --dry-run failed");
  assert.match(dryRun.stdout, /Home:      main/);
  assert.match(dryRun.stdout, /Work ref:  work\//);
  assert.doesNotMatch(dryRun.stdout, /Sessions:/);
  assert.doesNotMatch(dryRun.stdout, /Session:/);
  assert.match(dryRun.stdout, /writable\s+workspace\/writable \(repo-writable, base develop\)/);
  assert.match(dryRun.stdout, /read-only workspace\/readonly \(repo-readonly, ref develop \(base main\)\)/);
  assert.match(dryRun.stdout, /convention\.md :gist/);
  assert.match(dryRun.stdout, /assertion\.md :gist/);
  assert.doesNotMatch(dryRun.stdout, /old-colon-scope\.md/);
  assert.match(dryRun.stdout, /decision\.md :gist/);
  assert.match(dryRun.stdout, /runbook-workon\.md :gist/);
  assert.match(dryRun.stdout, /runbook-repo\.md :gist/);
  assert.match(dryRun.stdout, /foundation\.md :body scope=app/);
  assert.match(dryRun.stdout, /No files written\./);
  assert.doesNotMatch(readFileSync(bridgeExclude, "utf8"), /BEGIN nosedive-managed/);

  const rc = readNosediveRc(join(bridge, "workspace"));
  assert.equal(rc.bridgeDir, bridge);
  assert.equal(rc.workspaceDir, join(bridge, "workspace"));
  assert.equal(rc.backlogDir, join(bridge, "backlog"));
  assert.equal(rc.kbDir, join(bridge, "kb"));
  assert.equal(rc.homeBranch, "main");
  assert.equal(rc.workBranchPrefix, "work/");
  assert.deepEqual(rc.current, {
    effort: "yaml-frontmatter/YamlFrontmatter.md",
  });

  writeNosediveRcCurrent(bridge, { effort: "other-effort/OtherEffort.md" });
  assert.match(readFileSync(join(bridge, ".nosediverc"), "utf8"), /custom-scalar: keep-me/);
  assert.deepEqual(readNosediveRc(bridge).current, {
    effort: "other-effort/OtherEffort.md",
  });
  writeNosediveRcCurrent(bridge);
  assert.doesNotMatch(readFileSync(join(bridge, ".nosediverc"), "utf8"), /^current:/m);
  writeNosediveRcCurrent(bridge, {
    effort: "yaml-frontmatter/YamlFrontmatter.md",
  });

  const verboseBacklog = run(["dump-backlog", "--verbose"], bridge);
  assertOk(verboseBacklog, "dump-backlog --verbose failed");
  assertContainsPath(verboseBacklog.stdout, join(bridge, "backlog", "yaml-frontmatter", "YamlFrontmatter.md"));
  assertContainsPath(verboseBacklog.stdout, join(bridge, "backlog", "other-effort", "OtherEffort.md"));
  assertContainsPath(verboseBacklog.stdout, join(bridge, "backlog", "gogglebox", "auth-refactor", "AuthRefactor.md"));
  assert.match(verboseBacklog.stdout, /[├└]─ gogglebox\//);
  assert.match(verboseBacklog.stdout, /\[shaping\] auth-refactor\.gogglebox/);
  assert.doesNotMatch(verboseBacklog.stdout, /\[unknown\] gogglebox/);
  assert.doesNotMatch(verboseBacklog.stdout, /\.artifacts/);

  const apply = run(["apply"], bridge);
  assertOk(apply, "apply failed");
  assert.match(apply.stdout, /tracked generated file marked skip-worktree: .*CLAUDE\.md/);
  assert.equal(existsSync(join(bridge, "CLAUDE.md")), true);
  assert.equal(existsSync(join(bridge, "workspace", "CLAUDE.md")), true);
  assert.equal(existsSync(join(bridge, "workspace", "writable", "CLAUDE.md")), true);
  assert.equal(existsSync(join(bridge, "workspace", "readonly", "app", "CLAUDE.md")), true);

  const bridgeDoc = readFileSync(join(bridge, "CLAUDE.md"), "utf8");
  assertGeneratedFrontmatter(bridgeDoc, "CLAUDE.md");
  assert.match(bridgeDoc, /# Foundation Body/);
  assert.match(bridgeDoc, /## Available Runbooks/);
  assert.match(bridgeDoc, /If the user asks what runbooks are available or what they can do, answer from this list with runbook names and gists\./);
  assert.match(bridgeDoc, /If the user asks to do something that sounds like one of these runbooks, read the full source doc before taking the runbook\./);
  assert.match(bridgeDoc, /### `workon`/);
  assert.match(bridgeDoc, /Start working on an effort\./);
  assert.match(bridgeDoc, /Source: `kb[\\/]runbook-workon\.md`/);
  assert.doesNotMatch(bridgeDoc, /Run the workon flow after reading this doc\./);

  const workspaceDoc = readFileSync(join(bridge, "workspace", "CLAUDE.md"), "utf8");
  assertGeneratedFrontmatter(workspaceDoc, "CLAUDE.md", [`effort: "yaml-frontmatter/YamlFrontmatter.md"`]);
  assert.doesNotMatch(workspaceDoc, /# Agent Instructions/);
  assert.match(workspaceDoc, /# YAML frontmatter/);
  assert.match(workspaceDoc, /Build the YAML-aware workspace work order\./);
  assert.doesNotMatch(workspaceDoc, /Bridge:/);
  assert.doesNotMatch(workspaceDoc, /Effort:/);
  assertContainsPath(workspaceDoc, join(bridge, "workspace", "writable"));
  assertContainsPath(workspaceDoc, join(bridge, "workspace", "readonly"));
  assert.match(workspaceDoc, /Only the paths listed above are part of this effort\. Do not inspect or edit other directories unless the user explicitly expands the effort\./);
  assert.doesNotMatch(workspaceDoc, /other workspace directories/);
  assertContainsPath(workspaceDoc, join(bridge, "backlog", "yaml-frontmatter", "YamlFrontmatter.md"));
  assertContainsPath(workspaceDoc, join(bridge, "backlog", "other-effort", "OtherEffort.md"));

  const writableDoc = readFileSync(join(bridge, "workspace", "writable", "CLAUDE.md"), "utf8");
  assertGeneratedFrontmatter(writableDoc, "CLAUDE.md", [
    `effort: "yaml-frontmatter/YamlFrontmatter.md"`,
    `repo-id: "repo-writable"`,
    `scope-path: "."`,
  ]);
  assert.doesNotMatch(writableDoc, /Target:/);
  assert.match(writableDoc, /Quoted gist: colon, "quotes", and `backticks` survive YAML parsing\./);
  assert.match(writableDoc, /Scoped assertion gists render by default\./);
  assert.doesNotMatch(writableDoc, /Old multi-colon scopes do not render\./);
  assert.match(writableDoc, /Scoped decision gists render by default\./);
  assert.match(writableDoc, /### `repo-runbook\.test`/);
  assert.match(writableDoc, /Repo-scoped runbooks render as gists\./);
  const writableAgentsDoc = readFileSync(join(bridge, "workspace", "writable", "AGENTS.md"), "utf8");
  assertGeneratedFrontmatter(writableAgentsDoc, "AGENTS.md", [
    `effort: "yaml-frontmatter/YamlFrontmatter.md"`,
    `repo-id: "repo-writable"`,
    `scope-path: "."`,
  ]);

  const bodyDoc = readFileSync(join(bridge, "workspace", "writable", "app", "CLAUDE.md"), "utf8");
  assertGeneratedFrontmatter(bodyDoc, "CLAUDE.md", [
    `effort: "yaml-frontmatter/YamlFrontmatter.md"`,
    `repo-id: "repo-writable"`,
    `scope-path: "app"`,
  ]);
  assert.match(bodyDoc, /# Foundation Body/);
  assert.match(bodyDoc, /Body rendered from valid YAML frontmatter\./);

  const readOnlyDoc = readFileSync(join(bridge, "workspace", "readonly", "app", "CLAUDE.md"), "utf8");
  assertGeneratedFrontmatter(readOnlyDoc, "CLAUDE.md", [
    `effort: "yaml-frontmatter/YamlFrontmatter.md"`,
    `repo-id: "repo-readonly"`,
    `scope-path: "app"`,
  ]);
  assert.match(readOnlyDoc, /Read-only For This Effort/);

  for (const [label, excludePath] of [
    ["bridge", bridgeExclude],
    ["writable", writableExclude],
    ["readonly", readonlyExclude],
  ]) {
    const excludeText = readFileSync(excludePath, "utf8");
    assert.match(excludeText, new RegExp(`# user ${label} exclude`));
    assert.match(excludeText, /# BEGIN nosedive-managed exclude/);
    assert.match(excludeText, /# kb: 019f5651-5539-76f5-b6bd-351d300194eb/);
    assert.match(excludeText, /# owner: nosedive apply/);
    assert.match(excludeText, /^CLAUDE\.md$/m);
    assert.match(excludeText, /^AGENTS\.md$/m);
    assert.doesNotMatch(excludeText, /^\/CLAUDE\.md$/m);
    assert.match(excludeText, /# END nosedive-managed exclude/);
  }

  assert.match(runTool("git", ["-C", writableRoot, "ls-files", "-v", "CLAUDE.md"], root).stdout, /^S /);
  assertOk(runTool("git", ["check-ignore", "app/CLAUDE.md"], writableRoot), "nested CLAUDE.md should be ignored by bare exclude pattern");
  assertOk(runTool("git", ["check-ignore", "app/AGENTS.md"], readonlyRoot), "nested AGENTS.md should be ignored by bare exclude pattern");

  const activeBridge = join(tmp, "active-bridge");
  mkdirSync(join(activeBridge, "kb"), { recursive: true });
  write(
    join(activeBridge, ".nosediverc"),
    `kb: ./kb
`,
  );
  write(
    join(activeBridge, "kb", "active-foundation.md"),
    `---
kind: foundation
id: active-foundation
name: active-foundation
gist: "Active foundation docs render from kb-only config."
---

# Active Foundation

Bridge foundation body renders without a scope.
`,
  );
  write(
    join(activeBridge, "kb", "active-convention.md"),
    `---
kind: convention
id: active-convention
name: active.test
gist: "Scoped convention should not render from kb-only config."
scopes:
  - repo-active
---

# Active convention body
`,
  );
  write(
    join(activeBridge, "kb", "active-runbook.md"),
    `---
kind: runbook
id: active-runbook
name: active
gist: "Active bridge runbook renders from dot scope."
scopes:
  - .
---

# Active runbook body
`,
  );

  const activeDryRun = run(["apply", "--dry-run"], activeBridge);
  assertOk(activeDryRun, "kb-only apply --dry-run failed");
  assert.match(activeDryRun.stdout, /Workspace: \(not configured\)/);
  assert.match(activeDryRun.stdout, /Effort:    \(not configured\)/);
  assert.match(activeDryRun.stdout, /Bridge docs:/);
  assert.match(activeDryRun.stdout, /active-foundation\.md :body/);
  assert.match(activeDryRun.stdout, /active-runbook\.md :gist/);
  assert.doesNotMatch(activeDryRun.stdout, /active-convention\.md :gist/);

  const activeApply = run(["apply"], activeBridge);
  assertOk(activeApply, "kb-only apply failed");
  assert.equal(existsSync(join(activeBridge, "CLAUDE.md")), true);
  assert.equal(existsSync(join(activeBridge, "AGENTS.md")), true);
  const activeDoc = readFileSync(join(activeBridge, "CLAUDE.md"), "utf8");
  assertGeneratedFrontmatter(activeDoc, "CLAUDE.md");
  assert.doesNotMatch(activeDoc, /^effort:/m);
  assert.doesNotMatch(activeDoc, /^repo-id:/m);
  assert.doesNotMatch(activeDoc, /^scope-path:/m);
  assert.doesNotMatch(activeDoc, /# Agent Instructions/);
  assert.doesNotMatch(activeDoc, /Target:/);
  assert.match(activeDoc, /# Active Foundation/);
  assert.match(activeDoc, /Bridge foundation body renders without a scope\./);
  assert.match(activeDoc, /### `active`/);
  assert.match(activeDoc, /Active bridge runbook renders from dot scope\./);
  assert.doesNotMatch(activeDoc, /# Active runbook body/);
  assert.doesNotMatch(activeDoc, /Scoped convention should not render from kb-only config\./);
  assert.equal(existsSync(join(activeBridge, "workspace", "CLAUDE.md")), false);

  const pitchBridge = join(tmp, "pitch-bridge");
  mkdirSync(join(pitchBridge, "backlog", "parent-effort"), { recursive: true });
  mkdirSync(join(pitchBridge, "backlog", "gogglebox", "auth-refactor"), { recursive: true });
  mkdirSync(join(pitchBridge, "backlog", "other", "auth-refactor"), { recursive: true });
  runTool("git", ["init", "-b", "main"], pitchBridge);
  runTool("git", ["config", "user.name", "Nosedive Test"], pitchBridge);
  runTool("git", ["config", "user.email", "nosedive@example.invalid"], pitchBridge);
  write(
    join(pitchBridge, ".nosediverc"),
    `backlog: ./backlog
kb: ./kb
`,
  );
  write(
    join(pitchBridge, "backlog", "parent-effort", "ParentEffort.md"),
    `---
phase: shaping
gist: "Parent effort for pitch tests."
---

# Parent Effort
`,
  );
  write(
    join(pitchBridge, "backlog", "gogglebox", "auth-refactor", "AuthRefactor.md"),
    `---
phase: shaping
gist: "Gogglebox auth parent."
---

# Auth Refactor
`,
  );
  write(
    join(pitchBridge, "backlog", "other", "auth-refactor", "AuthRefactor.md"),
    `---
phase: shaping
gist: "Other auth parent."
---

# Auth Refactor
`,
  );
  runTool(
    "git",
    [
      "add",
      ".nosediverc",
      "backlog/parent-effort/ParentEffort.md",
      "backlog/gogglebox/auth-refactor/AuthRefactor.md",
      "backlog/other/auth-refactor/AuthRefactor.md",
    ],
    pitchBridge,
  );
  runTool("git", ["commit", "-m", "Seed pitch bridge"], pitchBridge);

  const pitchByChain = run(
    [
      "pitch",
      "child-effort-from-slug-chain",
      "--gist",
      "Short slug-chain child gist.",
      "--pitch",
      "Longer pitch text for the slug-chain child.",
      "--parent",
      "parent-effort",
    ],
    pitchBridge,
  );
  assertOk(pitchByChain, "pitch by slug chain failed");
  assert.match(pitchByChain.stdout, /Pitched .*ChildEffortFromSlugChain\.md/);
  assert.doesNotMatch(pitchByChain.stdout, /Pushed bridge branch/);

  const childByChain = join(pitchBridge, "backlog", "parent-effort", "child-effort-from-slug-chain", "ChildEffortFromSlugChain.md");
  assert.equal(existsSync(childByChain), true);
  const childByChainText = readFileSync(childByChain, "utf8");
  assert.match(childByChainText, /phase: framing/);
  assert.match(childByChainText, /gist: "Short slug-chain child gist\."/);
  assert.match(childByChainText, /# Child Effort From Slug Chain/);
  assert.match(childByChainText, /Longer pitch text for the slug-chain child\./);

  const pitchByPath = run(["pitch", "child-effort-from-path", "--gist=Path child gist.", "--parent", "backlog/parent-effort/ParentEffort.md"], pitchBridge);
  assertOk(pitchByPath, "pitch by backlog path failed");
  const childByPath = join(pitchBridge, "backlog", "parent-effort", "child-effort-from-path", "ChildEffortFromPath.md");
  assert.equal(existsSync(childByPath), true);
  const childByPathText = readFileSync(childByPath, "utf8");
  assert.match(childByPathText, /gist: "Path child gist\."/);
  assert.match(childByPathText, /Path child gist\./);

  const pitchByDomainChain = run(["pitch", "domain-child", "--gist=Domain child gist.", "--parent", "auth-refactor.gogglebox"], pitchBridge);
  assertOk(pitchByDomainChain, "pitch by domain-qualified slug chain failed");
  const domainChild = join(pitchBridge, "backlog", "gogglebox", "auth-refactor", "domain-child", "DomainChild.md");
  assert.equal(existsSync(domainChild), true);
  assert.match(readFileSync(domainChild, "utf8"), /gist: "Domain child gist\."/);

  const pitchByNamespace = run(["pitch", "namespace-child", "--gist=Namespace child gist.", "--parent", "gogglebox"], pitchBridge);
  assertOk(pitchByNamespace, "pitch by namespace parent failed");
  const namespaceChild = join(pitchBridge, "backlog", "gogglebox", "namespace-child", "NamespaceChild.md");
  assert.equal(existsSync(namespaceChild), true);
  assert.match(readFileSync(namespaceChild, "utf8"), /gist: "Namespace child gist\."/);

  const pitchByNamespacePath = run(["pitch", "namespace-path-child", "--gist=Namespace path child gist.", "--parent", "backlog/gogglebox"], pitchBridge);
  assertOk(pitchByNamespacePath, "pitch by namespace parent path failed");
  const namespacePathChild = join(pitchBridge, "backlog", "gogglebox", "namespace-path-child", "NamespacePathChild.md");
  assert.equal(existsSync(namespacePathChild), true);
  assert.match(readFileSync(namespacePathChild, "utf8"), /gist: "Namespace path child gist\."/);

  const pitchWithSlugOnly = run(["pitch", "top-level-slug-only"], pitchBridge);
  assertOk(pitchWithSlugOnly, "pitch with slug only failed");
  const topLevel = join(pitchBridge, "backlog", "top-level-slug-only", "TopLevelSlugOnly.md");
  assert.equal(existsSync(topLevel), true);
  const topLevelText = readFileSync(topLevel, "utf8");
  assert.match(topLevelText, /gist: "Top Level Slug Only"/);
  assert.match(topLevelText, /Top Level Slug Only/);

  const pitchLog = runTool("git", ["log", "--oneline", "--max-count=3"], pitchBridge).stdout;
  assert.doesNotMatch(pitchLog, /Pitch top-level-slug-only/);
  assert.doesNotMatch(pitchLog, /Pitch domain-child/);
  assert.doesNotMatch(pitchLog, /Pitch child-effort-from-path/);
  assert.doesNotMatch(pitchLog, /Pitch child-effort-from-slug-chain/);
  assert.match(pitchLog, /Seed pitch bridge/);
  const pitchStatus = runTool("git", ["status", "--short", "--untracked-files=all"], pitchBridge).stdout;
  assert.match(pitchStatus, /\?\? backlog\/parent-effort\/child-effort-from-slug-chain\/ChildEffortFromSlugChain\.md/);
  assert.match(pitchStatus, /\?\? backlog\/parent-effort\/child-effort-from-path\/ChildEffortFromPath\.md/);
  assert.match(pitchStatus, /\?\? backlog\/gogglebox\/auth-refactor\/domain-child\/DomainChild\.md/);
  assert.match(pitchStatus, /\?\? backlog\/gogglebox\/namespace-child\/NamespaceChild\.md/);
  assert.match(pitchStatus, /\?\? backlog\/gogglebox\/namespace-path-child\/NamespacePathChild\.md/);
  assert.match(pitchStatus, /\?\? backlog\/top-level-slug-only\/TopLevelSlugOnly\.md/);

  const addRepoBridge = join(tmp, "add-repo-bridge");
  mkdirSync(join(addRepoBridge, "backlog", "feature"), { recursive: true });
  mkdirSync(join(addRepoBridge, "backlog", "held-feature"), { recursive: true });
  mkdirSync(join(addRepoBridge, "kb"), { recursive: true });
  mkdirSync(join(addRepoBridge, "workspace", "alpha"), { recursive: true });
  mkdirSync(join(addRepoBridge, "workspace", "beta"), { recursive: true });
  mkdirSync(join(addRepoBridge, "workspace", "gamma"), { recursive: true });
  runTool("git", ["init", "-b", "main"], addRepoBridge);
  runTool("git", ["config", "user.email", "dev@example.invalid"], addRepoBridge);
  runTool("git", ["config", "user.name", "Nosedive Dev"], addRepoBridge);
  runTool("git", ["init", "-b", "main"], join(addRepoBridge, "workspace", "alpha"));
  runTool("git", ["init", "-b", "main"], join(addRepoBridge, "workspace", "beta"));
  runTool("git", ["init", "-b", "main"], join(addRepoBridge, "workspace", "gamma"));
  const longFeatureGist =
    "Feature effort for add-repo tests with a deliberately long one-line gist that must not be wrapped or otherwise reformatted when repos are appended.";
  write(
    join(addRepoBridge, ".nosediverc"),
    `workspace: ./workspace
backlog: ./backlog
kb: ./kb
`,
  );
  write(
    join(addRepoBridge, "backlog", "feature", "Feature.md"),
    `---
phase: building
gist: "${longFeatureGist}"
custom: keep-me
repos:
  - repo-alpha
---

# Feature

Do not rewrite this body.
`,
  );
  write(
    join(addRepoBridge, "backlog", "held-feature", "HeldFeature.md"),
    `---
phase: building
gist: "Held feature effort for add-repo tests."
repos:
  - repo-alpha
---

# Held Feature

Active workspace docs should be regenerated.
`,
  );
  write(
    join(addRepoBridge, "kb", "repo-alpha.md"),
    `---
kind: repo
id: repo-alpha
name: alpha
gist: "Alpha repo."
meta:
  path: workspace/alpha
---
`,
  );
  write(
    join(addRepoBridge, "kb", "repo-beta.md"),
    `---
kind: repo
id: repo-beta
name: beta
gist: "Beta repo."
meta:
  path: workspace/beta
---
`,
  );
  write(
    join(addRepoBridge, "kb", "repo-gamma.md"),
    `---
kind: repo
id: repo-gamma
name: gamma
gist: "Gamma repo."
meta:
  path: workspace/gamma
---
`,
  );
  write(
    join(addRepoBridge, "kb", "repo-duplicate-a.md"),
    `---
kind: repo
id: repo-duplicate-a
name: duplicate
gist: "First duplicate repo."
meta:
  path: workspace/duplicate-a
---
`,
  );
  write(
    join(addRepoBridge, "kb", "repo-duplicate-b.md"),
    `---
kind: repo
id: repo-duplicate-b
name: duplicate
gist: "Second duplicate repo."
meta:
  path: workspace/duplicate-b
---
`,
  );
  write(
    join(addRepoBridge, "kb", "gamma-convention.md"),
    `---
kind: convention
id: gamma-convention
name: gamma.test
gist: "Gamma convention generated after add-repo."
scopes:
  - repo-gamma
---

# Gamma convention body
`,
  );
  write(
    join(addRepoBridge, "kb", "held-dive.md"),
    `---
kind: dive
id: held-dive
name: held-feature.abcdef
gist: "Held dive for add-repo tests."
effort: backlog/held-feature/HeldFeature.md
meta:
  diver: dev@example.invalid
---

# Held dive
`,
  );

  const addById = run(["add-repo", "repo-beta", "--effort", "../../backlog/feature/Feature.md"], join(addRepoBridge, "workspace", "alpha"));
  assertOk(addById, "add-repo by id failed");
  assert.match(addById.stdout, /Added repo-beta to .*Feature\.md/);
  const featureAfterId = readFileSync(join(addRepoBridge, "backlog", "feature", "Feature.md"), "utf8");
  assert.match(featureAfterId, new RegExp(`gist: "${escapeRegExp(longFeatureGist)}"\\ncustom: keep-me`));
  assert.match(featureAfterId, /custom: keep-me/);
  assert.match(featureAfterId, /repos:\n  - repo-alpha\n  - repo-beta/);
  assert.match(featureAfterId, /Do not rewrite this body\./);

  const addWithModifiers = run(["add-repo", "gamma", "--effort", "feature", "--ref", "release/candidate", "--read-only", "--no-apply"], addRepoBridge);
  assertOk(addWithModifiers, "add-repo with modifiers failed");
  const featureAfterModifiers = readFileSync(join(addRepoBridge, "backlog", "feature", "Feature.md"), "utf8");
  assert.match(featureAfterModifiers, /  - repo-gamma@release\/candidate:ro/);
  assert.equal(existsSync(join(addRepoBridge, "workspace", "gamma", "CLAUDE.md")), false);

  const duplicateAdd = run(["add-repo", "repo-beta", "--effort", "feature"], addRepoBridge);
  assert.notEqual(duplicateAdd.status, 0, "duplicate add-repo unexpectedly succeeded");
  assert.match(duplicateAdd.stderr, /effort already includes repo repo-beta/);

  const ambiguousAdd = run(["add-repo", "duplicate", "--effort", "feature"], addRepoBridge);
  assert.notEqual(ambiguousAdd.status, 0, "ambiguous add-repo unexpectedly succeeded");
  assert.match(ambiguousAdd.stderr, /repo name is ambiguous: duplicate/);
  assert.match(ambiguousAdd.stderr, /repo-duplicate-a/);
  assert.match(ambiguousAdd.stderr, /repo-duplicate-b/);

  const addFromHeldDive = run(["add-repo", "gamma"], addRepoBridge);
  assertOk(addFromHeldDive, "add-repo from held dive failed");
  assert.match(addFromHeldDive.stdout, /Added repo-gamma to .*HeldFeature\.md/);
  assert.match(addFromHeldDive.stdout, /Wrote workspace docs/);
  const heldFeatureAfterAdd = readFileSync(join(addRepoBridge, "backlog", "held-feature", "HeldFeature.md"), "utf8");
  assert.match(heldFeatureAfterAdd, /repos:\n  - repo-alpha\n  - repo-gamma/);
  const gammaDoc = readFileSync(join(addRepoBridge, "workspace", "gamma", "CLAUDE.md"), "utf8");
  assertGeneratedFrontmatter(gammaDoc, "CLAUDE.md", [
    `effort: "held-feature/HeldFeature.md"`,
    `repo-id: "repo-gamma"`,
    `scope-path: "."`,
  ]);
  assert.match(gammaDoc, /Gamma convention generated after add-repo\./);

  write(
    join(bridge, "kb", "bad.md"),
    `---
kind: convention
id: bad-doc
name: bad
gist: "unterminated
---
`,
  );

  const invalid = run(["apply", "--dry-run"], bridge);
  assert.notEqual(invalid.status, 0, "invalid YAML unexpectedly succeeded");
  assert.match(invalid.stderr, /invalid YAML in frontmatter in .*bad\.md/);
  rmSync(join(bridge, "kb", "bad.md"), { force: true });

  write(
    join(bridge, "backlog", "yaml-frontmatter", "YamlFrontmatter.md"),
    `---
phase: building
gist: "Exercise valid YAML: quoted effort gist"
repos:
  - repo-writable:rw
---

# YAML frontmatter

Build the YAML-aware workspace work order.
`,
  );

  const invalidRepoFlag = run(["apply", "--dry-run"], bridge);
  assert.notEqual(invalidRepoFlag.status, 0, "invalid repo flag unexpectedly succeeded");
  assert.match(invalidRepoFlag.stderr, /invalid effort repo flag in .*YamlFrontmatter\.md: repo-writable:rw \(unsupported flag: rw\)/);

  const initHelp = run(["init", "--help"], root);
  assertOk(initHelp, "init --help failed");
  assert.match(initHelp.stdout, /Usage: nosedive init/);

  const initBridge = join(tmp, "init-bridge");
  mkdirSync(initBridge, { recursive: true });

  const initFresh = run(["init"], initBridge, "\n\n\n\n\n\n");
  assertOk(initFresh, "init on empty directory failed");
  assert.match(initFresh.stdout, /Wrote \.nosediverc/);
  const freshRc = readFileSync(join(initBridge, ".nosediverc"), "utf8");
  assert.equal(
    freshRc,
    [
      "workspace: ./workspace",
      "backlog: ./backlog",
      "kb: ./kb",
      "home-branch: main",
      "work-branch-prefix: work/",
      "agents:",
      "  - copilot",
      "",
    ].join("\n"),
  );

  const initReprompt = run(["init"], initBridge, "\n\n\n\n\nbogus\ncopilot,claude\n");
  assertOk(initReprompt, "init re-run with invalid agent failed");
  assert.match(initReprompt.stderr, /unknown agent\(s\): bogus \(options: copilot, claude\)/);
  const repromptedRc = readFileSync(join(initBridge, ".nosediverc"), "utf8");
  assert.match(repromptedRc, /workspace: \.\/workspace/);
  assert.match(repromptedRc, /agents:\n  - copilot\n  - claude\n$/);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
