import assert from "node:assert/strict";
import {
	existsSync,
	mkdtempSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	realpathSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { pathToFileURL } from "node:url";

const root = process.cwd();
const cli = join(root, "dist", "cli.js");
const lib = join(root, "dist", "nosedive.js");
const { readNosediveRc, writeNosediveRcCurrent } = await import(pathToFileURL(lib).href);
const tmp = mkdtempSync(join(tmpdir(), "nosedive-test-"));
const packageFoundationDocs = [
	"00000000-0000-7434-9b1d-72a777ca61f7.md",
	"0000000f-4240-7a62-8f61-a85b4c364560.md",
	"0000001e-8480-79d6-8e3d-00222452c904.md",
	"0000002d-c6c0-7354-a306-7624c2db8283.md",
	"0000004c-4b40-7ee6-a8de-1f3b50de9a0b.md",
];
const packageFoundationDocCount = packageFoundationDocs.length;
const packageNonFoundationDoc = "00cb3908-d040-795e-ae14-89cd1aeeaaf8.md";
const gitLocalEnvKeys = [
	"GIT_ALTERNATE_OBJECT_DIRECTORIES",
	"GIT_COMMON_DIR",
	"GIT_DIR",
	"GIT_INDEX_FILE",
	"GIT_OBJECT_DIRECTORY",
	"GIT_PREFIX",
	"GIT_WORK_TREE",
];

function write(path, content) {
	mkdirSync(dirname(path), { recursive: true });
	writeFileSync(path, content, "utf8");
}

function run(args, cwd, input) {
	return spawnSync(process.execPath, [cli, ...args], {
		cwd,
		encoding: "utf8",
		input,
	});
}

const gitSafeBareConfigArgs = ["-c", "safe.bareRepository=all"];

function runGit(args, cwd, { expectOk = true } = {}) {
	const env = { ...process.env };
	for (const key of gitLocalEnvKeys) delete env[key];
	const result = spawnSync("git", [...gitSafeBareConfigArgs, ...args], {
		cwd,
		encoding: "utf8",
		env,
	});
	if (expectOk) {
		assert.equal(
			result.status,
			0,
			`git ${args.join(" ")} failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
		);
	}
	return result;
}

function runTool(command, args, cwd) {
	if (command === "git") return runGit(args, cwd);
	const env = { ...process.env };
	for (const key of gitLocalEnvKeys) delete env[key];
	const result = spawnSync(command, args, { cwd, encoding: "utf8", env });
	assert.equal(
		result.status,
		0,
		`${command} ${args.join(" ")} failed\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`,
	);
	return result;
}

function runGitUnchecked(args, cwd) {
	return runGit(args, cwd, { expectOk: false });
}

function assertOk(result, label) {
	assert.equal(result.status, 0, `${label}\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);
}

function escapeRegExp(value) {
	return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function assertContainsPath(text, path) {
	assert.match(text, new RegExp(escapeRegExp(path)));
}

function gitCommonDir(cwd) {
	const raw = runTool("git", ["rev-parse", "--git-common-dir"], cwd).stdout.trim();
	return realpathSync(isAbsolute(raw) ? raw : resolve(cwd, raw));
}

function assertGeneratedFrontmatter(text, filename, fields = []) {
	const expected = [
		"---",
		`generated-by: "nosedive"`,
		`generated-file: "${filename}"`,
		"do-not-edit: true",
		`gist: "Generated by nosedive from kb; do not edit by hand."`,
		...fields,
		"---",
		"",
	].join("\n");
	assert.equal(
		text.startsWith(expected),
		true,
		`expected generated frontmatter:\n${expected}\nactual start:\n${text.slice(0, 300)}`,
	);
}

try {
	const importOnly = spawnSync(
		process.execPath,
		["-e", `import(${JSON.stringify(pathToFileURL(lib).href)})`],
		{
			cwd: root,
			encoding: "utf8",
		},
	);
	assertOk(importOnly, "library import failed");
	assert.equal(importOnly.stdout, "", "library import unexpectedly wrote to stdout");
	assert.equal(importOnly.stderr, "", "library import unexpectedly wrote to stderr");

	const version = run(["version"], root);
	assertOk(version, "version command failed");
	assert.match(version.stdout.trim(), /^(\d+\.\d+\.\d+(?:-\d+)?|0\.0\.0-dev)$/);

	const help = run(["--help"], root);
	assertOk(help, "--help command failed");
	assert.match(help.stdout, /Usage: nosedive <command>/);
	assert.match(help.stdout, /mint/);
	assert.match(help.stdout, /init/);
	assert.match(help.stdout, /dump-backlog/);
	assert.match(help.stdout, /list-dives/);
	assert.match(help.stdout, /pitch/);
	assert.match(help.stdout, /hydrate-repo\.workspace/);
	assert.match(help.stdout, /dehydrate-repo\.workspace/);
	assert.match(help.stdout, /add-repo/);
	assert.match(help.stdout, /nuke/);

	const minted = run(["mint", "1997-08-29T02:14:00-04:00", "2"], root);
	assertOk(minted, "mint command failed");
	const mintedLines = minted.stdout.trim().split(/\r?\n/);
	assert.equal(mintedLines.length, 2, "mint should print one UUID per line");
	assert.match(
		mintedLines[0],
		/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
	);
	assert.match(
		mintedLines[1],
		/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
	);
	assert.equal(
		mintedLines[0] < mintedLines[1],
		true,
		"mint count mode should advance timestamps by 1ms and sort lexicographically",
	);

	const mintedNow = run(["mint"], root);
	assertOk(mintedNow, "mint default timestamp command failed");
	assert.match(
		mintedNow.stdout.trim(),
		/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
	);

	const bridge = join(tmp, "bridge");
	mkdirSync(join(bridge, "workspace", "writable", "app"), { recursive: true });
	mkdirSync(join(bridge, "workspace", "readonly", "app"), { recursive: true });
	mkdirSync(join(bridge, "backlog", "yaml-frontmatter"), { recursive: true });
	mkdirSync(join(bridge, "backlog", "other-effort"), { recursive: true });
	mkdirSync(join(bridge, "backlog", "gogglebox", "auth-refactor"), {
		recursive: true,
	});
	mkdirSync(join(bridge, "backlog", "yaml-frontmatter", ".artifacts"), {
		recursive: true,
	});
	mkdirSync(join(bridge, "kb"), { recursive: true });

	const writableRoot = join(bridge, "workspace", "writable");
	const readonlyRoot = join(bridge, "workspace", "readonly");
	const bridgeExclude = join(bridge, ".git", "info", "exclude");
	const writableExclude = join(writableRoot, ".git", "info", "exclude");
	const readonlyExclude = join(readonlyRoot, ".git", "info", "exclude");

	runTool("git", ["init"], bridge);
	runTool("git", ["init"], writableRoot);
	runTool("git", ["init"], readonlyRoot);
	write(join(bridge, "AGENTS.md"), "# Tracked bridge instructions\n");
	runTool("git", ["add", "AGENTS.md"], bridge);
	runTool(
		"git",
		[
			"-c",
			"user.name=Nosedive Test",
			"-c",
			"user.email=nosedive@example.invalid",
			"commit",
			"-m",
			"Track AGENTS",
		],
		bridge,
	);
	write(bridgeExclude, "# user bridge exclude\n*.bridge-local\n");
	write(writableExclude, "# user writable exclude\n*.writable-local\n");
	write(readonlyExclude, "# user readonly exclude\n*.readonly-local\n");
	write(join(writableRoot, "CLAUDE.md"), "# Tracked local instructions\n");
	runTool("git", ["add", "CLAUDE.md"], writableRoot);
	runTool(
		"git",
		[
			"-c",
			"user.name=Nosedive Test",
			"-c",
			"user.email=nosedive@example.invalid",
			"commit",
			"-m",
			"Track CLAUDE",
		],
		writableRoot,
	);

	write(
		join(bridge, ".nosediverc"),
		`workspace: ./workspace
backlog: ./backlog
kb: ./kb
home-branch: main
work-branch-prefix: work/
pilot-name: Pilot Person
pilot-email: pilot@example.invalid
agents:
  - copilot
  - claude
custom-scalar: keep-me
current:
  effort: yaml-frontmatter/YamlFrontmatter.md
`,
	);
	write(
		join(bridge, "workspace", ".nosedive-ref"),
		`id: active-dive
`,
	);
	write(
		join(bridge, "backlog", "yaml-frontmatter", "YamlFrontmatter.md"),
		`---
phase: building
gist: "Exercise valid YAML: quoted effort gist"
repos:
  - repo-writable
  - repo-readonly@develop:ro
pending-dives:
  - pending-dive
  - missing-dive
  - wrong-effort-dive
---

# YAML frontmatter

Build the YAML-aware workspace work order.
`,
	);
	write(
		join(bridge, "backlog", "other-effort", "OtherEffort.md"),
		`---
phase: framing
gist: "Another open effort: visible in verbose backlog output."
---

# Other effort
`,
	);
	write(
		join(bridge, "backlog", "gogglebox", "README.md"),
		`# Gogglebox Domain

This markdown file documents the domain and must not make it an effort.
`,
	);
	write(
		join(bridge, "backlog", "gogglebox", "auth-refactor", "AuthRefactor.md"),
		`---
phase: shaping
gist: "Domain-qualified effort under a project namespace."
---

# Auth Refactor
`,
	);
	write(
		join(bridge, "backlog", "yaml-frontmatter", ".artifacts", "proof.md"),
		`# Proof

Artifact markdown must not be discovered as an effort.
`,
	);
	write(
		join(bridge, "kb", "repo-writable.md"),
		`---
kind: repo
id: repo-writable
name: writable
gist: "Writable repo: quoted gist"
meta:
  path: workspace/writable
  base-branch: develop
---
`,
	);
	write(
		join(bridge, "kb", "repo-readonly.md"),
		`---
kind: repo
id: repo-readonly
name: readonly
gist: "Read-only repo: quoted gist"
meta:
  path: workspace/readonly
---
`,
	);
	write(
		join(bridge, "kb", "convention.md"),
		`---
kind: convention
id: convention-doc
name: convention.test
gist: "Quoted gist: colon, \\"quotes\\", and \`backticks\` survive YAML parsing."
scopes:
  - repo-writable: {}
  - repo-readonly:
      path: app
      render: gist
---

# Convention body
`,
	);
	write(
		join(bridge, "kb", "assertion.md"),
		`---
kind: assertion
id: assertion-doc
name: assertion.test
gist: "Scoped assertion gists render by default."
scopes:
  - repo-writable:
      ref: abc123
      mode: ro
      render: gist
---

# Assertion body
`,
	);
	write(
		join(bridge, "kb", "old-colon-scope.md"),
		`---
kind: assertion
id: old-colon-scope
name: old-colon-scope.test
gist: "Old multi-colon scopes do not render."
scopes:
  - repo-unused:
      mode: ro
      render: gist
---

# Old colon scope body
`,
	);
	write(
		join(bridge, "kb", "decision.md"),
		`---
kind: decision
id: decision-doc
name: decision.test
gist: "Scoped decision gists render by default."
scopes:
  - repo-writable: {}
links:
  - foundation-doc#frontmatter
---

# Decision body
`,
	);
	write(
		join(bridge, "kb", "runbook-workon.md"),
		`---
kind: runbook
id: runbook-workon
name: workon
gist: "Start working on an effort."
scopes:
  - .:
      render: gist
---

# Workon

Run the workon flow after reading this doc.
`,
	);
	write(
		join(bridge, "kb", "runbook-repo.md"),
		`---
kind: runbook
id: runbook-repo
name: repo-runbook.test
gist: "Repo-scoped runbooks render as gists."
scopes:
  - repo-writable: {}
---

# Repo runbook body
`,
	);
	write(
		join(bridge, "kb", "active-dive.md"),
		`---
kind: dive
id: active-dive
name: yaml-frontmatter.abcdef
gist: "Active dive for apply tests."
scopes:
  - repo-writable: {}
  - repo-readonly:
      ref: develop
      mode: ro
meta:
  effort: backlog/yaml-frontmatter/YamlFrontmatter.md
  diver: pilot@example.invalid
---

# Active dive
`,
	);
	write(
		join(bridge, "kb", "pending-dive.md"),
		`---
kind: dive
id: pending-dive
name: yaml-frontmatter.pending
gist: "Pending dive ready to pick up."
scopes:
  - repo-writable: {}
meta:
  effort: backlog/yaml-frontmatter/YamlFrontmatter.md
  diver:
---

# Pending dive
`,
	);
	write(
		join(bridge, "kb", "foundation.md"),
		`---
kind: foundation
id: foundation-doc
name: foundation.test
gist: "Foundation gist: body render uses markdown body."
scopes:
  - repo-writable:
      path: app
      render: body
---

# Foundation Body

Body rendered from valid YAML frontmatter.
`,
	);
	write(
		join(bridge, "kb", "completed-dive.md"),
		`---
kind: dive
id: completed-dive
name: yaml-frontmatter.completed
gist: "Completed dive preserved as provenance."
scopes:
  - repo-writable: {}
meta:
  effort: backlog/yaml-frontmatter/YamlFrontmatter.md
  diver:
---

# Completed dive
`,
	);
	write(
		join(bridge, "kb", "wrong-effort-dive.md"),
		`---
kind: dive
id: wrong-effort-dive
name: other-effort.wrong
gist: "Wrong effort pending ref fixture."
scopes:
  - repo-writable: {}
meta:
  effort: backlog/other-effort/OtherEffort.md
  diver:
---

# Wrong effort dive
`,
	);

	const dryRun = run(["apply", "--dry-run"], bridge);
	assertOk(dryRun, "apply --dry-run failed");
	assert.match(dryRun.stdout, /Home:      main/);
	assert.match(dryRun.stdout, /Work ref:  work\//);
	assert.match(dryRun.stdout, /Pilot:     Pilot Person <pilot@example\.invalid>/);
	assert.match(dryRun.stdout, /Dive:      active-dive/);
	assert.match(dryRun.stdout, /Tags:      pilot-is-set/);
	assert.doesNotMatch(dryRun.stdout, /Sessions:/);
	assert.doesNotMatch(dryRun.stdout, /Session:/);
	assert.match(dryRun.stdout, /writable\s+workspace\/writable \(repo-writable, base develop\)/);
	assert.match(
		dryRun.stdout,
		/read-only workspace\/readonly \(repo-readonly, ref develop \(base main\)\)/,
	);
	assert.doesNotMatch(dryRun.stdout, /Workspace docs:/);
	assert.doesNotMatch(dryRun.stdout, /Repo docs:/);
	assert.doesNotMatch(dryRun.stdout, /convention\.md :gist/);
	assert.doesNotMatch(dryRun.stdout, /assertion\.md :gist/);
	assert.doesNotMatch(dryRun.stdout, /old-colon-scope\.md/);
	assert.doesNotMatch(dryRun.stdout, /decision\.md :gist/);
	assert.match(dryRun.stdout, /runbook-workon\.md :gist/);
	assert.doesNotMatch(dryRun.stdout, /runbook-repo\.md :gist/);
	assert.match(dryRun.stdout, /foundation\.md :body/);
	assert.match(dryRun.stdout, /No files written\./);
	assert.doesNotMatch(readFileSync(bridgeExclude, "utf8"), /BEGIN nosedive-managed/);

	const rc = readNosediveRc(join(bridge, "workspace"));
	assert.equal(rc.bridgeDir, bridge);
	assert.equal(rc.workspaceDir, join(bridge, "workspace"));
	assert.equal(rc.backlogDir, join(bridge, "backlog"));
	assert.equal(rc.kbDir, join(bridge, "kb"));
	assert.equal(rc.homeBranch, "main");
	assert.equal(rc.workBranchPrefix, "work/");
	assert.deepEqual(rc.current, {
		effort: "yaml-frontmatter/YamlFrontmatter.md",
	});

	writeNosediveRcCurrent(bridge, { effort: "other-effort/OtherEffort.md" });
	assert.match(readFileSync(join(bridge, ".nosediverc"), "utf8"), /custom-scalar: keep-me/);
	assert.deepEqual(readNosediveRc(bridge).current, {
		effort: "other-effort/OtherEffort.md",
	});
	writeNosediveRcCurrent(bridge);
	assert.doesNotMatch(readFileSync(join(bridge, ".nosediverc"), "utf8"), /^current:/m);
	writeNosediveRcCurrent(bridge, {
		effort: "yaml-frontmatter/YamlFrontmatter.md",
	});

	const verboseBacklog = run(["dump-backlog", "--verbose"], bridge);
	assertOk(verboseBacklog, "dump-backlog --verbose failed");
	assertContainsPath(
		verboseBacklog.stdout,
		join(bridge, "backlog", "yaml-frontmatter", "YamlFrontmatter.md"),
	);
	assertContainsPath(
		verboseBacklog.stdout,
		join(bridge, "backlog", "other-effort", "OtherEffort.md"),
	);
	assertContainsPath(
		verboseBacklog.stdout,
		join(bridge, "backlog", "gogglebox", "auth-refactor", "AuthRefactor.md"),
	);
	assert.match(verboseBacklog.stdout, /[├└]─ gogglebox\//);
	assert.match(verboseBacklog.stdout, /\[shaping\] auth-refactor\.gogglebox/);
	assert.doesNotMatch(verboseBacklog.stdout, /\[unknown\] gogglebox/);
	assert.doesNotMatch(verboseBacklog.stdout, /\.artifacts/);

	const listDives = run(["list-dives", "yaml-frontmatter"], bridge);
	assertOk(listDives, "list-dives failed");
	assert.match(listDives.stdout, /Effort: yaml-frontmatter\/YamlFrontmatter\.md/);
	assert.match(listDives.stdout, /Pending:\n  - pending-dive yaml-frontmatter\.pending/);
	assert.match(
		listDives.stdout,
		/Working:\n  - active-dive yaml-frontmatter\.abcdef diver=pilot@example\.invalid/,
	);
	assert.doesNotMatch(listDives.stdout, /completed-dive/);
	assert.match(listDives.stdout, /pending dive missing-dive is missing from kb/);
	assert.match(
		listDives.stdout,
		/pending dive wrong-effort-dive does not point back at yaml-frontmatter\/YamlFrontmatter\.md/,
	);

	const listDivesHistory = run(["list-dives", "yaml-frontmatter", "--include-historical"], bridge);
	assertOk(listDivesHistory, "list-dives --include-historical failed");
	assert.match(
		listDivesHistory.stdout,
		/Historical:\n  - completed-dive yaml-frontmatter\.completed/,
	);

	const listDivesJson = run(["list-dives", "yaml-frontmatter", "--json"], bridge);
	assertOk(listDivesJson, "list-dives --json failed");
	const parsedListDives = JSON.parse(listDivesJson.stdout);
	assert.deepEqual(
		parsedListDives.pending.map((dive) => dive.id),
		["pending-dive"],
	);
	assert.deepEqual(
		parsedListDives.working.map((dive) => dive.id),
		["active-dive"],
	);
	assert.deepEqual(parsedListDives.historical, []);
	assert.equal(parsedListDives.warnings.length, 2);

	const apply = run(["apply"], bridge);
	assertOk(apply, "apply failed");
	assert.doesNotMatch(apply.stdout, /tracked generated file marked skip-worktree: .*CLAUDE\.md/);
	assert.equal(existsSync(join(bridge, "CLAUDE.md")), true);
	assert.equal(existsSync(join(bridge, "AGENTS.md")), true);
	assert.equal(existsSync(join(bridge, "workspace", "CLAUDE.md")), false);
	assert.equal(existsSync(join(bridge, "workspace", "writable", "CLAUDE.md")), true);
	assert.equal(
		readFileSync(join(bridge, "workspace", "writable", "CLAUDE.md"), "utf8"),
		"# Tracked local instructions\n",
	);
	assert.equal(existsSync(join(bridge, "workspace", "writable", "AGENTS.md")), false);
	assert.equal(existsSync(join(bridge, "workspace", "readonly", "app", "CLAUDE.md")), false);

	const bridgeDoc = readFileSync(join(bridge, "CLAUDE.md"), "utf8");
	assertGeneratedFrontmatter(bridgeDoc, "CLAUDE.md");
	assert.match(bridgeDoc, /# Foundation Body/);
	assert.match(readFileSync(join(bridge, "AGENTS.md"), "utf8"), /# Foundation Body/);
	assert.match(bridgeDoc, /## Available Runbooks/);
	assert.match(
		bridgeDoc,
		/If the user asks what runbooks are available or what they can do, answer from this list with runbook names and gists\./,
	);
	assert.match(
		bridgeDoc,
		/If the user asks to do something that sounds like one of these runbooks, read the full source doc before taking the runbook\./,
	);
	assert.match(bridgeDoc, /### `workon`/);
	assert.match(bridgeDoc, /Start working on an effort\./);
	assert.match(bridgeDoc, /Source: `kb[\\/]runbook-workon\.md`/);
	assert.doesNotMatch(bridgeDoc, /Run the workon flow after reading this doc\./);

	const bridgeExcludeText = readFileSync(bridgeExclude, "utf8");
	assert.match(bridgeExcludeText, /# user bridge exclude/);
	assert.match(bridgeExcludeText, /# BEGIN nosedive-managed exclude/);
	assert.match(bridgeExcludeText, /# kb: 019f5651-5539-76f5-b6bd-351d300194eb/);
	assert.match(bridgeExcludeText, /# owner: nosedive apply/);
	assert.match(bridgeExcludeText, /^AGENTS\.md$/m);
	assert.match(bridgeExcludeText, /^CLAUDE\.md$/m);
	assert.doesNotMatch(bridgeExcludeText, /^\/CLAUDE\.md$/m);
	assert.match(bridgeExcludeText, /# END nosedive-managed exclude/);
	assert.doesNotMatch(readFileSync(writableExclude, "utf8"), /BEGIN nosedive-managed/);
	assert.doesNotMatch(readFileSync(readonlyExclude, "utf8"), /BEGIN nosedive-managed/);

	const guardedNuke = run(["nuke"], bridge);
	assert.equal(guardedNuke.status, 1);
	assert.match(guardedNuke.stderr, /rerun with --instructions/);

	write(
		writableExclude,
		`${readFileSync(writableExclude, "utf8").replace(/\n*$/, "\n")}# BEGIN nosedive-managed exclude\n# owner: workspace fixture\nCLAUDE.md\n# END nosedive-managed exclude\n`,
	);

	const nuke = run(["nuke", "--instructions"], bridge);
	assertOk(nuke, "nuke --instructions failed");
	assert.match(nuke.stdout, /Nuked managed instruction state/);
	const bridgeExcludeAfterNuke = readFileSync(bridgeExclude, "utf8");
	assert.match(bridgeExcludeAfterNuke, /# user bridge exclude/);
	assert.doesNotMatch(bridgeExcludeAfterNuke, /BEGIN nosedive-managed exclude/);
	assert.match(readFileSync(writableExclude, "utf8"), /BEGIN nosedive-managed exclude/);
	assert.equal(readFileSync(join(bridge, "AGENTS.md"), "utf8"), "# Tracked bridge instructions\n");
	assert.match(runTool("git", ["-C", bridge, "ls-files", "-v", "AGENTS.md"], root).stdout, /^H /);

	assert.match(
		runTool("git", ["-C", writableRoot, "ls-files", "-v", "CLAUDE.md"], root).stdout,
		/^H /,
	);

	const activeBridge = join(tmp, "active-bridge");
	mkdirSync(join(activeBridge, "kb"), { recursive: true });
	runTool("git", ["init", "-b", "main"], activeBridge);
	write(
		join(activeBridge, ".nosediverc"),
		`kb: ./kb
agents:
  - copilot
`,
	);
	write(
		join(activeBridge, "kb", "active-foundation.md"),
		`---
kind: foundation
id: active-foundation
name: active-foundation
gist: "Active foundation docs render from kb-only config."
---

# Active Foundation

Bridge foundation body renders without a scope.
`,
	);
	write(
		join(activeBridge, "kb", "active-convention.md"),
		`---
kind: convention
id: active-convention
name: active.test
gist: "Scoped convention should not render from kb-only config."
scopes:
  - repo-active: {}
---

# Active convention body
`,
	);
	write(
		join(activeBridge, "kb", "active-runbook.md"),
		`---
kind: runbook
id: active-runbook
name: active
gist: "Active bridge runbook renders from dot scope."
scopes:
  - .:
      render: gist
---

# Active runbook body
`,
	);
	write(
		join(activeBridge, "kb", "empty-workspace-foundation.md"),
		`---
kind: foundation
id: empty-workspace-foundation
name: empty-workspace-foundation
gist: "Workspace-empty foundation renders only while the workspace is absent or empty."
meta:
  include-if-any:
    - workspace-is-empty
---

# Empty Workspace Foundation

This renders before workspace setup.
`,
	);
	write(
		join(activeBridge, "kb", "pilot-foundation.md"),
		`---
kind: foundation
id: pilot-foundation
name: pilot-foundation
gist: "Pilot foundation renders only when pilot is configured."
meta:
  include-if-all:
    - pilot-is-set
---

# Pilot Foundation

This renders only when pilot is set.
`,
	);
	write(
		join(activeBridge, "kb", "conflicting-foundation.md"),
		`---
kind: foundation
id: conflicting-foundation
name: conflicting-foundation
gist: "Conflicting foundation filters should skip with a warning."
meta:
  include-if-any:
    - workspace-is-empty
  exclude-if-any:
    - pilot-is-set
---

# Conflicting Foundation

This should be skipped.
`,
	);
	write(
		join(activeBridge, "kb", "unmatched-conflicting-foundation.md"),
		`---
kind: foundation
id: unmatched-conflicting-foundation
name: unmatched-conflicting-foundation
gist: "Nonmatching scoped foundation filters should not be evaluated."
scopes:
  - repo-active: {}
meta:
  include-if-any:
    - workspace-is-empty
  exclude-if-any:
    - pilot-is-set
---

# Unmatched Conflicting Foundation

This should not be considered when no active dive repo matches it.
`,
	);

	const activeDryRun = run(["apply", "--dry-run"], activeBridge);
	assertOk(activeDryRun, "kb-only apply --dry-run failed");
	assert.match(activeDryRun.stdout, /Workspace: \(not configured\)/);
	assert.match(activeDryRun.stdout, /Effort:    \(not configured\)/);
	assert.match(activeDryRun.stdout, /Tags:      workspace-is-empty/);
	assert.match(activeDryRun.stdout, /Bridge docs:/);
	assert.match(activeDryRun.stdout, /AGENTS\.md/);
	assert.doesNotMatch(activeDryRun.stdout, /CLAUDE\.md/);
	assert.match(activeDryRun.stdout, /active-foundation\.md :body/);
	assert.match(activeDryRun.stdout, /empty-workspace-foundation\.md :body/);
	assert.doesNotMatch(activeDryRun.stdout, /pilot-foundation\.md :body/);
	assert.doesNotMatch(activeDryRun.stdout, /conflicting-foundation\.md :body/);
	assert.doesNotMatch(activeDryRun.stdout, /unmatched-conflicting-foundation\.md/);
	assert.match(
		activeDryRun.stdout,
		/foundation doc kb[\\/]conflicting-foundation\.md has multiple include\/exclude meta filters; skipping/,
	);
	assert.doesNotMatch(
		activeDryRun.stdout,
		/foundation doc kb[\\/]unmatched-conflicting-foundation\.md has multiple include\/exclude meta filters; skipping/,
	);
	assert.match(activeDryRun.stdout, /active-runbook\.md :gist/);
	assert.doesNotMatch(activeDryRun.stdout, /active-convention\.md :gist/);

	const activeApply = run(["apply"], activeBridge);
	assertOk(activeApply, "kb-only apply failed");
	assert.equal(existsSync(join(activeBridge, "CLAUDE.md")), false);
	assert.equal(existsSync(join(activeBridge, "AGENTS.md")), true);
	const activeDoc = readFileSync(join(activeBridge, "AGENTS.md"), "utf8");
	assertGeneratedFrontmatter(activeDoc, "AGENTS.md");
	assert.doesNotMatch(activeDoc, /^effort:/m);
	assert.doesNotMatch(activeDoc, /^repo-id:/m);
	assert.doesNotMatch(activeDoc, /^scope-path:/m);
	assert.doesNotMatch(activeDoc, /# Agent Instructions/);
	assert.doesNotMatch(activeDoc, /Target:/);
	assert.match(activeDoc, /# Active Foundation/);
	assert.match(activeDoc, /Bridge foundation body renders without a scope\./);
	assert.match(activeDoc, /# Empty Workspace Foundation/);
	assert.doesNotMatch(activeDoc, /# Pilot Foundation/);
	assert.doesNotMatch(activeDoc, /# Conflicting Foundation/);
	assert.match(activeDoc, /### `active`/);
	assert.match(activeDoc, /Active bridge runbook renders from dot scope\./);
	assert.doesNotMatch(activeDoc, /# Active runbook body/);
	assert.doesNotMatch(activeDoc, /Scoped convention should not render from kb-only config\./);
	assert.equal(existsSync(join(activeBridge, "workspace", "CLAUDE.md")), false);

	const tagBridge = join(tmp, "tag-bridge");
	mkdirSync(join(tagBridge, "kb"), { recursive: true });
	runTool("git", ["init", "-b", "main"], tagBridge);
	write(
		join(tagBridge, ".nosediverc"),
		`backlog: ./missing-backlog
kb: ./kb
agents:
  - copilot
`,
	);
	write(
		join(tagBridge, "kb", "missing-backlog-foundation.md"),
		`---
kind: foundation
id: missing-backlog-foundation
name: missing-backlog-foundation
gist: "Missing-backlog foundation renders only when configured backlog is absent."
meta:
  include-if-any:
    - backlog-is-missing
---

# Missing Backlog Foundation

This renders when the configured backlog directory does not exist.
`,
	);
	write(
		join(tagBridge, "kb", "ignored-backlog-foundation.md"),
		`---
kind: foundation
id: ignored-backlog-foundation
name: ignored-backlog-foundation
gist: "Ignored-backlog foundation renders only when configured backlog is ignored."
meta:
  include-if-any:
    - backlog-is-ignored
---

# Ignored Backlog Foundation

This renders when the configured backlog path is ignored by git status.
`,
	);

	const missingBacklogDryRun = run(["apply", "--dry-run"], tagBridge);
	assertOk(missingBacklogDryRun, "missing-backlog apply --dry-run failed");
	assert.match(missingBacklogDryRun.stdout, /Tags:      backlog-is-missing, workspace-is-empty/);
	assert.match(missingBacklogDryRun.stdout, /missing-backlog-foundation\.md :body/);
	assert.doesNotMatch(missingBacklogDryRun.stdout, /ignored-backlog-foundation\.md :body/);

	write(
		join(tagBridge, ".nosediverc"),
		`backlog: ./ignored-backlog
kb: ./kb
agents:
  - copilot
`,
	);
	write(join(tagBridge, ".gitignore"), "ignored-backlog/\n");
	write(join(tagBridge, "ignored-backlog", "placeholder.txt"), "ignored by git status\n");
	const ignoredBacklogDryRun = run(["apply", "--dry-run"], tagBridge);
	assertOk(ignoredBacklogDryRun, "ignored-backlog apply --dry-run failed");
	assert.match(ignoredBacklogDryRun.stdout, /Tags:      backlog-is-ignored, workspace-is-empty/);
	assert.match(ignoredBacklogDryRun.stdout, /ignored-backlog-foundation\.md :body/);
	assert.doesNotMatch(ignoredBacklogDryRun.stdout, /missing-backlog-foundation\.md :body/);

	const pitchBridge = join(tmp, "pitch-bridge");
	mkdirSync(join(pitchBridge, "backlog", "parent-effort"), { recursive: true });
	mkdirSync(join(pitchBridge, "backlog", "gogglebox", "auth-refactor"), {
		recursive: true,
	});
	mkdirSync(join(pitchBridge, "backlog", "other", "auth-refactor"), {
		recursive: true,
	});
	runTool("git", ["init", "-b", "main"], pitchBridge);
	runTool("git", ["config", "user.name", "Nosedive Test"], pitchBridge);
	runTool("git", ["config", "user.email", "nosedive@example.invalid"], pitchBridge);
	write(
		join(pitchBridge, ".nosediverc"),
		`backlog: ./backlog
kb: ./kb
`,
	);
	write(
		join(pitchBridge, "backlog", "parent-effort", "ParentEffort.md"),
		`---
phase: shaping
gist: "Parent effort for pitch tests."
---

# Parent Effort
`,
	);
	write(
		join(pitchBridge, "backlog", "gogglebox", "auth-refactor", "AuthRefactor.md"),
		`---
phase: shaping
gist: "Gogglebox auth parent."
---

# Auth Refactor
`,
	);
	write(
		join(pitchBridge, "backlog", "other", "auth-refactor", "AuthRefactor.md"),
		`---
phase: shaping
gist: "Other auth parent."
---

# Auth Refactor
`,
	);
	runTool(
		"git",
		[
			"add",
			".nosediverc",
			"backlog/parent-effort/ParentEffort.md",
			"backlog/gogglebox/auth-refactor/AuthRefactor.md",
			"backlog/other/auth-refactor/AuthRefactor.md",
		],
		pitchBridge,
	);
	runTool("git", ["commit", "-m", "Seed pitch bridge"], pitchBridge);

	const pitchByChain = run(
		[
			"pitch",
			"child-effort-from-slug-chain",
			"--gist",
			"Short slug-chain child gist.",
			"--pitch",
			"Longer pitch text for the slug-chain child.",
			"--parent",
			"parent-effort",
		],
		pitchBridge,
	);
	assertOk(pitchByChain, "pitch by slug chain failed");
	assert.match(pitchByChain.stdout, /Pitched .*ChildEffortFromSlugChain\.md/);
	assert.doesNotMatch(pitchByChain.stdout, /Pushed bridge branch/);

	const childByChain = join(
		pitchBridge,
		"backlog",
		"parent-effort",
		"child-effort-from-slug-chain",
		"ChildEffortFromSlugChain.md",
	);
	assert.equal(existsSync(childByChain), true);
	const childByChainText = readFileSync(childByChain, "utf8");
	assert.match(childByChainText, /phase: framing/);
	assert.match(childByChainText, /gist: "Short slug-chain child gist\."/);
	assert.match(childByChainText, /# Child Effort From Slug Chain/);
	assert.match(childByChainText, /Longer pitch text for the slug-chain child\./);

	const pitchByPath = run(
		[
			"pitch",
			"child-effort-from-path",
			"--gist=Path child gist.",
			"--parent",
			"backlog/parent-effort/ParentEffort.md",
		],
		pitchBridge,
	);
	assertOk(pitchByPath, "pitch by backlog path failed");
	const childByPath = join(
		pitchBridge,
		"backlog",
		"parent-effort",
		"child-effort-from-path",
		"ChildEffortFromPath.md",
	);
	assert.equal(existsSync(childByPath), true);
	const childByPathText = readFileSync(childByPath, "utf8");
	assert.match(childByPathText, /gist: "Path child gist\."/);
	assert.match(childByPathText, /Path child gist\./);

	const pitchByDomainChain = run(
		["pitch", "domain-child", "--gist=Domain child gist.", "--parent", "auth-refactor.gogglebox"],
		pitchBridge,
	);
	assertOk(pitchByDomainChain, "pitch by domain-qualified slug chain failed");
	const domainChild = join(
		pitchBridge,
		"backlog",
		"gogglebox",
		"auth-refactor",
		"domain-child",
		"DomainChild.md",
	);
	assert.equal(existsSync(domainChild), true);
	assert.match(readFileSync(domainChild, "utf8"), /gist: "Domain child gist\."/);

	const pitchByNamespace = run(
		["pitch", "namespace-child", "--gist=Namespace child gist.", "--parent", "gogglebox"],
		pitchBridge,
	);
	assertOk(pitchByNamespace, "pitch by namespace parent failed");
	const namespaceChild = join(
		pitchBridge,
		"backlog",
		"gogglebox",
		"namespace-child",
		"NamespaceChild.md",
	);
	assert.equal(existsSync(namespaceChild), true);
	assert.match(readFileSync(namespaceChild, "utf8"), /gist: "Namespace child gist\."/);

	const pitchByNamespacePath = run(
		[
			"pitch",
			"namespace-path-child",
			"--gist=Namespace path child gist.",
			"--parent",
			"backlog/gogglebox",
		],
		pitchBridge,
	);
	assertOk(pitchByNamespacePath, "pitch by namespace parent path failed");
	const namespacePathChild = join(
		pitchBridge,
		"backlog",
		"gogglebox",
		"namespace-path-child",
		"NamespacePathChild.md",
	);
	assert.equal(existsSync(namespacePathChild), true);
	assert.match(readFileSync(namespacePathChild, "utf8"), /gist: "Namespace path child gist\."/);

	const pitchWithSlugOnly = run(["pitch", "top-level-slug-only"], pitchBridge);
	assertOk(pitchWithSlugOnly, "pitch with slug only failed");
	const topLevel = join(pitchBridge, "backlog", "top-level-slug-only", "TopLevelSlugOnly.md");
	assert.equal(existsSync(topLevel), true);
	const topLevelText = readFileSync(topLevel, "utf8");
	assert.match(topLevelText, /gist: "Top Level Slug Only"/);
	assert.match(topLevelText, /Top Level Slug Only/);

	const pitchLog = runTool("git", ["log", "--oneline", "--max-count=3"], pitchBridge).stdout;
	assert.doesNotMatch(pitchLog, /Pitch top-level-slug-only/);
	assert.doesNotMatch(pitchLog, /Pitch domain-child/);
	assert.doesNotMatch(pitchLog, /Pitch child-effort-from-path/);
	assert.doesNotMatch(pitchLog, /Pitch child-effort-from-slug-chain/);
	assert.match(pitchLog, /Seed pitch bridge/);
	const pitchStatus = runTool(
		"git",
		["status", "--short", "--untracked-files=all"],
		pitchBridge,
	).stdout;
	assert.match(
		pitchStatus,
		/\?\? backlog\/parent-effort\/child-effort-from-slug-chain\/ChildEffortFromSlugChain\.md/,
	);
	assert.match(
		pitchStatus,
		/\?\? backlog\/parent-effort\/child-effort-from-path\/ChildEffortFromPath\.md/,
	);
	assert.match(
		pitchStatus,
		/\?\? backlog\/gogglebox\/auth-refactor\/domain-child\/DomainChild\.md/,
	);
	assert.match(pitchStatus, /\?\? backlog\/gogglebox\/namespace-child\/NamespaceChild\.md/);
	assert.match(
		pitchStatus,
		/\?\? backlog\/gogglebox\/namespace-path-child\/NamespacePathChild\.md/,
	);
	assert.match(pitchStatus, /\?\? backlog\/top-level-slug-only\/TopLevelSlugOnly\.md/);

	const addRepoBridge = join(tmp, "add-repo-bridge");
	mkdirSync(join(addRepoBridge, "backlog", "feature"), { recursive: true });
	mkdirSync(join(addRepoBridge, "backlog", "held-feature"), {
		recursive: true,
	});
	mkdirSync(join(addRepoBridge, "kb"), { recursive: true });
	mkdirSync(join(addRepoBridge, "workspace", "alpha"), { recursive: true });
	mkdirSync(join(addRepoBridge, "workspace", "beta"), { recursive: true });
	mkdirSync(join(addRepoBridge, "workspace", "gamma"), { recursive: true });
	runTool("git", ["init", "-b", "main"], addRepoBridge);
	runTool("git", ["config", "user.email", "dev@example.invalid"], addRepoBridge);
	runTool("git", ["config", "user.name", "Nosedive Dev"], addRepoBridge);
	runTool("git", ["init", "-b", "main"], join(addRepoBridge, "workspace", "alpha"));
	runTool("git", ["init", "-b", "main"], join(addRepoBridge, "workspace", "beta"));
	runTool("git", ["init", "-b", "main"], join(addRepoBridge, "workspace", "gamma"));
	const longFeatureGist =
		"Feature effort for add-repo tests with a deliberately long one-line gist that must not be wrapped or otherwise reformatted when repos are appended.";
	write(
		join(addRepoBridge, ".nosediverc"),
		`workspace: ./workspace
backlog: ./backlog
kb: ./kb
`,
	);
	write(
		join(addRepoBridge, "backlog", "feature", "Feature.md"),
		`---
phase: building
gist: "${longFeatureGist}"
custom: keep-me
repos:
  - repo-alpha
---

# Feature

Do not rewrite this body.
`,
	);
	write(
		join(addRepoBridge, "backlog", "held-feature", "HeldFeature.md"),
		`---
phase: building
gist: "Held feature effort for add-repo tests."
repos:
  - repo-alpha
---

# Held Feature

Active bridge docs should be regenerated.
`,
	);
	write(
		join(addRepoBridge, "kb", "repo-alpha.md"),
		`---
kind: repo
id: repo-alpha
name: alpha
gist: "Alpha repo."
meta:
  path: workspace/alpha
---
`,
	);
	write(
		join(addRepoBridge, "kb", "repo-beta.md"),
		`---
kind: repo
id: repo-beta
name: beta
gist: "Beta repo."
meta:
  path: workspace/beta
---
`,
	);
	write(
		join(addRepoBridge, "kb", "repo-gamma.md"),
		`---
kind: repo
id: repo-gamma
name: gamma
gist: "Gamma repo."
meta:
  path: workspace/gamma
---
`,
	);
	write(
		join(addRepoBridge, "kb", "repo-duplicate-a.md"),
		`---
kind: repo
id: repo-duplicate-a
name: duplicate
gist: "First duplicate repo."
meta:
  path: workspace/duplicate-a
---
`,
	);
	write(
		join(addRepoBridge, "kb", "repo-duplicate-b.md"),
		`---
kind: repo
id: repo-duplicate-b
name: duplicate
gist: "Second duplicate repo."
meta:
  path: workspace/duplicate-b
---
`,
	);
	write(
		join(addRepoBridge, "kb", "gamma-convention.md"),
		`---
kind: convention
id: gamma-convention
name: gamma.test
gist: "Gamma convention generated after add-repo."
scopes:
  - repo-gamma: {}
---

# Gamma convention body
`,
	);
	write(
		join(addRepoBridge, "kb", "held-dive.md"),
		`---
kind: dive
id: held-dive
name: held-feature.abcdef
gist: "Held dive for add-repo tests."
effort: backlog/held-feature/HeldFeature.md
meta:
  diver: dev@example.invalid
---

# Held dive
`,
	);

	const addById = run(
		["add-repo", "repo-beta", "--effort", "../../backlog/feature/Feature.md"],
		join(addRepoBridge, "workspace", "alpha"),
	);
	assertOk(addById, "add-repo by id failed");
	assert.match(addById.stdout, /Added repo-beta to .*Feature\.md/);
	const featureAfterId = readFileSync(
		join(addRepoBridge, "backlog", "feature", "Feature.md"),
		"utf8",
	);
	assert.match(
		featureAfterId,
		new RegExp(`gist: "${escapeRegExp(longFeatureGist)}"\\ncustom: keep-me`),
	);
	assert.match(featureAfterId, /custom: keep-me/);
	assert.match(featureAfterId, /repos:\n  - repo-alpha\n  - repo-beta/);
	assert.match(featureAfterId, /Do not rewrite this body\./);

	const addWithModifiers = run(
		[
			"add-repo",
			"gamma",
			"--effort",
			"feature",
			"--ref",
			"release/candidate",
			"--read-only",
			"--no-apply",
		],
		addRepoBridge,
	);
	assertOk(addWithModifiers, "add-repo with modifiers failed");
	const featureAfterModifiers = readFileSync(
		join(addRepoBridge, "backlog", "feature", "Feature.md"),
		"utf8",
	);
	assert.match(featureAfterModifiers, /  - repo-gamma@release\/candidate:ro/);
	assert.equal(existsSync(join(addRepoBridge, "workspace", "gamma", "CLAUDE.md")), false);

	const duplicateAdd = run(["add-repo", "repo-beta", "--effort", "feature"], addRepoBridge);
	assert.notEqual(duplicateAdd.status, 0, "duplicate add-repo unexpectedly succeeded");
	assert.match(duplicateAdd.stderr, /effort already includes repo repo-beta/);

	const ambiguousAdd = run(["add-repo", "duplicate", "--effort", "feature"], addRepoBridge);
	assert.notEqual(ambiguousAdd.status, 0, "ambiguous add-repo unexpectedly succeeded");
	assert.match(ambiguousAdd.stderr, /repo name is ambiguous: duplicate/);
	assert.match(ambiguousAdd.stderr, /repo-duplicate-a/);
	assert.match(ambiguousAdd.stderr, /repo-duplicate-b/);

	const addFromHeldDive = run(["add-repo", "gamma"], addRepoBridge);
	assertOk(addFromHeldDive, "add-repo from held dive failed");
	assert.match(addFromHeldDive.stdout, /Added repo-gamma to .*HeldFeature\.md/);
	assert.match(addFromHeldDive.stdout, /Wrote bridge docs/);
	const heldFeatureAfterAdd = readFileSync(
		join(addRepoBridge, "backlog", "held-feature", "HeldFeature.md"),
		"utf8",
	);
	assert.match(heldFeatureAfterAdd, /repos:\n  - repo-alpha\n  - repo-gamma/);
	assert.equal(existsSync(join(addRepoBridge, "AGENTS.md")), true);
	assert.equal(existsSync(join(addRepoBridge, "workspace", "gamma", "CLAUDE.md")), false);
	assert.equal(existsSync(join(addRepoBridge, "workspace", "gamma", "AGENTS.md")), false);

	const hydrateBridge = join(tmp, "hydrate-bridge");
	const hydrateRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cd98";
	const fallbackRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cd99";
	const unsafeRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cd9a";
	const unresolvedRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cd9b";
	const otherRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cd9c";
	const emptyFailRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cd9d";
	const nameRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cd9e";
	const ambiguousRepoIdA = "019f8584-453f-79ea-9d53-5f1b20b4cd9f";
	const ambiguousRepoIdB = "019f8584-453f-79ea-9d53-5f1b20b4cda0";
	const staleWorktreeRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cda1";
	const staleCacheRepoId = "019f8584-453f-79ea-9d53-5f1b20b4cda2";
	mkdirSync(join(hydrateBridge, "kb"), { recursive: true });
	mkdirSync(join(hydrateBridge, "workspace"), { recursive: true });
	mkdirSync(join(hydrateBridge, "repos", "cloud-source"), { recursive: true });
	mkdirSync(join(hydrateBridge, "repos", "source"), { recursive: true });
	mkdirSync(join(hydrateBridge, "repos", "source-empty-fail"), {
		recursive: true,
	});
	runTool("git", ["init", "-b", "main"], hydrateBridge);
	runTool("git", ["config", "user.email", "hydrate@example.invalid"], hydrateBridge);
	runTool("git", ["config", "user.name", "Hydrate Dev"], hydrateBridge);

	const cloudSourceRepo = join(hydrateBridge, "repos", "cloud-source");
	runTool("git", ["init", "-b", "main"], cloudSourceRepo);
	runTool("git", ["config", "user.email", "hydrate@example.invalid"], cloudSourceRepo);
	runTool("git", ["config", "user.name", "Hydrate Dev"], cloudSourceRepo);
	write(join(cloudSourceRepo, "README.md"), "cloud main\n");
	runTool("git", ["add", "README.md"], cloudSourceRepo);
	runTool("git", ["commit", "-m", "cloud main commit"], cloudSourceRepo);
	runTool("git", ["branch", "release/candidate"], cloudSourceRepo);
	runTool("git", ["checkout", "release/candidate"], cloudSourceRepo);
	write(join(cloudSourceRepo, "README.md"), "cloud release\n");
	runTool("git", ["commit", "-am", "cloud release commit"], cloudSourceRepo);
	runTool("git", ["checkout", "main"], cloudSourceRepo);

	const sourceRepo = join(hydrateBridge, "repos", "source");
	runTool("git", ["init", "-b", "main"], sourceRepo);
	runTool("git", ["config", "user.email", "hydrate@example.invalid"], sourceRepo);
	runTool("git", ["config", "user.name", "Hydrate Dev"], sourceRepo);
	write(join(sourceRepo, "README.md"), "local main\n");
	runTool("git", ["add", "README.md"], sourceRepo);
	runTool("git", ["commit", "-m", "local main commit"], sourceRepo);
	runTool("git", ["branch", "release/candidate"], sourceRepo);
	runTool("git", ["checkout", "release/candidate"], sourceRepo);
	write(join(sourceRepo, "README.md"), "local release\n");
	runTool("git", ["commit", "-am", "local release commit"], sourceRepo);
	runTool("git", ["checkout", "main"], sourceRepo);
	const cloudMainCommit = runTool(
		"git",
		["rev-parse", "main^{commit}"],
		cloudSourceRepo,
	).stdout.trim();
	const localMainCommit = runTool("git", ["rev-parse", "main^{commit}"], sourceRepo).stdout.trim();
	assert.notEqual(
		cloudMainCommit,
		localMainCommit,
		"cloud and local fixture repos should have distinct commits",
	);

	const emptyFailSourceRepo = join(hydrateBridge, "repos", "source-empty-fail");
	runTool("git", ["init", "-b", "main"], emptyFailSourceRepo);
	runTool("git", ["config", "user.email", "hydrate@example.invalid"], emptyFailSourceRepo);
	runTool("git", ["config", "user.name", "Hydrate Dev"], emptyFailSourceRepo);
	write(join(emptyFailSourceRepo, "README.md"), "empty fail source\n");
	runTool("git", ["add", "README.md"], emptyFailSourceRepo);
	runTool("git", ["commit", "-m", "main commit"], emptyFailSourceRepo);

	write(
		join(hydrateBridge, ".nosediverc"),
		`workspace: ./workspace
backlog: ./backlog
kb: ./kb
`,
	);
	write(
		join(hydrateBridge, "kb", "repo-hydrate.md"),
		`---
kind: repo
id: ${hydrateRepoId}
name: hydrate
gist: "Hydrate repo test fixture"
meta:
  path: workspace/hydrated-target
  worktree-path: workspace/legacy-target
  remotes:
    cloud: repos/cloud-source
    local: repos/source
---
`,
	);
	write(
		join(hydrateBridge, "kb", "repo-fallback.md"),
		`---
kind: repo
id: ${fallbackRepoId}
name: fallback
gist: "Legacy path fallback fixture"
meta:
  worktree-path: workspace/fallback-target
  remotes:
    local: repos/source
---
`,
	);
	write(
		join(hydrateBridge, "kb", "repo-by-name.md"),
		`---
kind: repo
id: ${nameRepoId}
name: hydrate-by-name
gist: "Exact name hydrate fixture"
meta:
  path: workspace/name-target
  remotes:
    local: repos/source
---
`,
	);
	write(
		join(hydrateBridge, "kb", "repo-ambiguous-a.md"),
		`---
kind: repo
id: ${ambiguousRepoIdA}
name: duplicate-name
gist: "Ambiguous name fixture A"
meta:
  path: workspace/ambiguous-a
  remotes:
    local: repos/source
---
`,
	);
	write(
		join(hydrateBridge, "kb", "repo-ambiguous-b.md"),
		`---
kind: repo
id: ${ambiguousRepoIdB}
name: duplicate-name
gist: "Ambiguous name fixture B"
meta:
  path: workspace/ambiguous-b
  remotes:
    local: repos/source
---
`,
	);
	write(
		join(hydrateBridge, "kb", "repo-unsafe.md"),
		`---
kind: repo
id: ${unsafeRepoId}
name: unsafe
gist: "Unsafe path fixture"
meta:
  worktree-path: ../outside-target
  remotes:
    local: repos/source
---
`,
	);
	write(
		join(hydrateBridge, "kb", "repo-stale-worktree.md"),
		`---
kind: repo
id: ${staleWorktreeRepoId}
name: stale-worktree
gist: "Stale worktree registration fixture"
meta:
  path: workspace/stale-target
  remotes:
    local: repos/source
---
`,
	);
	write(
		join(hydrateBridge, "kb", "repo-stale-cache.md"),
		`---
kind: repo
id: ${staleCacheRepoId}
name: stale-cache
gist: "Stale cache fetch fixture"
meta:
  path: workspace/stale-cache-target
  remotes:
    cloud: repos/cloud-source
    local: repos/source
---
`,
	);

	const hydrateByName = run(["hydrate-repo.workspace", "hydrate-by-name"], hydrateBridge);
	assertOk(hydrateByName, "hydrate-repo.workspace exact name failed");
	assert.match(
		hydrateByName.stdout,
		new RegExp(
			`^created repo=${nameRepoId} path=workspace[\\\\/]name-target commit=[0-9a-f]{40}$`,
			"m",
		),
	);
	assert.equal(
		readFileSync(join(hydrateBridge, "workspace", "name-target", ".nosedive-ref"), "utf8"),
		`id: ${nameRepoId}\n`,
	);

	const ambiguousName = run(["hydrate-repo.workspace", "duplicate-name"], hydrateBridge);
	assert.notEqual(ambiguousName.status, 0, "ambiguous repo name unexpectedly succeeded");
	assert.match(
		ambiguousName.stderr,
		new RegExp(
			`repo name is ambiguous: duplicate-name \\(${ambiguousRepoIdA}, ${ambiguousRepoIdB}\\)`,
		),
	);
	assert.equal(
		existsSync(join(hydrateBridge, "workspace", "ambiguous-a")),
		false,
		"ambiguous repo name should not create first matching target path",
	);
	assert.equal(
		existsSync(join(hydrateBridge, "workspace", "ambiguous-b")),
		false,
		"ambiguous repo name should not create second matching target path",
	);

	const hydrateCreated = run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assertOk(hydrateCreated, "hydrate-repo.workspace create failed");
	assert.match(
		hydrateCreated.stdout,
		new RegExp(
			`^created repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target commit=[0-9a-f]{40}$`,
			"m",
		),
	);
	assert.equal(
		existsSync(join(hydrateBridge, "workspace", "legacy-target")),
		false,
		"deprecated meta.worktree-path should not win over meta.path",
	);
	const hydratedMarkerPath = join(hydrateBridge, "workspace", "hydrated-target", ".nosedive-ref");
	const hydratedTarget = join(hydrateBridge, "workspace", "hydrated-target");
	assert.equal(readFileSync(hydratedMarkerPath, "utf8"), `id: ${hydrateRepoId}\n`);
	const hydratedStatus = runTool(
		"git",
		["status", "--short", "--untracked-files=all"],
		hydratedTarget,
	).stdout;
	assert.equal(hydratedStatus, "", "repo ownership marker should not dirty the hydrated worktree");
	const hydratedExcludePathRaw = runTool(
		"git",
		["rev-parse", "--git-path", "info/exclude"],
		hydratedTarget,
	).stdout.trim();
	const hydratedExcludePath = isAbsolute(hydratedExcludePathRaw)
		? hydratedExcludePathRaw
		: resolve(hydratedTarget, hydratedExcludePathRaw);
	const hydratedExcludeText = readFileSync(hydratedExcludePath, "utf8");
	assert.match(hydratedExcludeText, /# BEGIN nosedive-managed repo-marker exclude/);
	assert.match(hydratedExcludeText, /^\.nosedive-ref$/m);
	assert.match(hydratedExcludeText, /# END nosedive-managed repo-marker exclude/);
	const hydrateCache = join(hydrateBridge, ".nosedive", "cache", hydrateRepoId);
	const hydrateCacheOrigin = runTool(
		"git",
		["remote", "get-url", "origin"],
		hydrateCache,
	).stdout.trim();
	assert.equal(
		hydrateCacheOrigin,
		cloudSourceRepo,
		"managed cache should prefer meta.remotes.cloud over local",
	);
	assert.equal(
		gitCommonDir(join(hydrateBridge, "workspace", "hydrated-target")),
		realpathSync(hydrateCache),
		"hydrated worktree should be attached to the managed cache",
	);
	assert.notEqual(
		gitCommonDir(join(hydrateBridge, "workspace", "hydrated-target")),
		gitCommonDir(sourceRepo),
		"hydrated worktree should not be attached directly to meta.remotes.local",
	);
	const hydratedHeadAfterCreate = runTool(
		"git",
		["rev-parse", "HEAD"],
		join(hydrateBridge, "workspace", "hydrated-target"),
	).stdout.trim();
	assert.equal(
		hydratedHeadAfterCreate,
		cloudMainCommit,
		"hydrated worktree should resolve default ref from the cloud-backed cache",
	);

	const staleCacheTarget = join(hydrateBridge, "workspace", "stale-cache-target");
	const staleManagedCache = join(hydrateBridge, ".nosedive", "cache", staleCacheRepoId);
	mkdirSync(dirname(staleManagedCache), { recursive: true });
	runTool("git", ["clone", "--bare", sourceRepo, staleManagedCache], hydrateBridge);
	runGitUnchecked(["config", "--unset-all", "remote.origin.fetch"], staleManagedCache);
	runTool("git", ["branch", "local/work", localMainCommit], staleManagedCache);
	assert.equal(
		runTool("git", ["rev-parse", "main^{commit}"], staleManagedCache).stdout.trim(),
		localMainCommit,
		"stale cache fixture should start behind the cloud source",
	);
	assert.notEqual(
		runGitUnchecked(["config", "--get-all", "remote.origin.fetch"], staleManagedCache).status,
		0,
		"stale cache fixture should start without a fetch refspec",
	);
	const staleCacheHydrate = run(["hydrate-repo.workspace", staleCacheRepoId], hydrateBridge);
	assertOk(
		staleCacheHydrate,
		"hydrate-repo.workspace should repair and fetch stale managed cache refs",
	);
	assert.match(
		staleCacheHydrate.stdout,
		new RegExp(
			`^created repo=${staleCacheRepoId} path=workspace[\\\\/]stale-cache-target commit=${cloudMainCommit}$`,
			"m",
		),
	);
	assert.equal(
		runTool("git", ["config", "--get-all", "remote.origin.fetch"], staleManagedCache).stdout.trim(),
		"+refs/heads/*:refs/remotes/origin/*",
		"hydrate should repair the managed cache fetch refspec",
	);
	assert.equal(
		runTool("git", ["remote", "get-url", "origin"], staleManagedCache).stdout.trim(),
		cloudSourceRepo,
		"hydrate should keep the managed cache pointed at the cloud remote",
	);
	assert.equal(
		runTool(
			"git",
			["rev-parse", "refs/remotes/origin/main^{commit}"],
			staleManagedCache,
		).stdout.trim(),
		cloudMainCommit,
		"hydrate should fetch cloud main into the managed cache remote-tracking refs before resolving refs",
	);
	assert.equal(
		runTool("git", ["rev-parse", "main^{commit}"], staleManagedCache).stdout.trim(),
		localMainCommit,
		"hydrate should not overwrite local cache branches when fetching cloud refs",
	);
	assert.equal(
		runTool("git", ["rev-parse", "local/work^{commit}"], staleManagedCache).stdout.trim(),
		localMainCommit,
		"hydrate fetch pruning should not delete local cache work branches",
	);
	assert.equal(
		runTool("git", ["rev-parse", "HEAD"], staleCacheTarget).stdout.trim(),
		cloudMainCommit,
		"hydrate should create the worktree at the fetched cloud main commit",
	);

	const detachedAfterCreate = runGitUnchecked(
		["symbolic-ref", "-q", "HEAD"],
		join(hydrateBridge, "workspace", "hydrated-target"),
	);
	assert.notEqual(detachedAfterCreate.status, 0, "hydrated worktree should be detached");
	const peerWorktree = join(hydrateBridge, "workspace", "hydrated-peer");
	runTool("git", ["worktree", "add", "--detach", peerWorktree, cloudMainCommit], hydrateCache);

	const hydrateNoop = run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assertOk(hydrateNoop, "hydrate-repo.workspace noop failed");
	assert.match(
		hydrateNoop.stdout,
		new RegExp(
			`^noop repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target commit=[0-9a-f]{40}$`,
			"m",
		),
	);

	const hydrateReadOnly = run(
		["hydrate-repo.workspace", hydrateRepoId, "--read-only"],
		hydrateBridge,
	);
	assertOk(hydrateReadOnly, "hydrate-repo.workspace read-only hardening failed");
	assert.match(
		hydrateReadOnly.stdout,
		new RegExp(
			`^updated repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target commit=[0-9a-f]{40}$`,
			"m",
		),
	);
	const pushUrlReadOnly = runTool(
		"git",
		["config", "--worktree", "--get", "remote.origin.pushurl"],
		join(hydrateBridge, "workspace", "hydrated-target"),
	).stdout.trim();
	assert.equal(pushUrlReadOnly, "no_push://disabled");
	const pushUrlReadOnlyFromOrdinaryConfig = runGitUnchecked(
		["config", "--get", "remote.origin.pushurl"],
		join(hydrateBridge, "workspace", "hydrated-target"),
	);
	assert.equal(
		pushUrlReadOnlyFromOrdinaryConfig.stdout.trim(),
		"no_push://disabled",
		"effective pushurl should still block pushes from the hydrated worktree",
	);
	const sharedCachePushUrlReadOnly = runGitUnchecked(
		["config", "--get", "remote.origin.pushurl"],
		hydrateCache,
	);
	assert.notEqual(
		sharedCachePushUrlReadOnly.status,
		0,
		"read-only hardening should not write pushurl into shared cache config",
	);
	const peerPushUrlReadOnly = runGitUnchecked(
		["config", "--get", "remote.origin.pushurl"],
		peerWorktree,
	);
	assert.notEqual(
		peerPushUrlReadOnly.status,
		0,
		"read-only hardening should not affect sibling worktrees",
	);
	const peerStillWorktree = runTool(
		"git",
		["rev-parse", "--is-inside-work-tree"],
		peerWorktree,
	).stdout.trim();
	assert.equal(
		peerStillWorktree,
		"true",
		"enabling worktree-local config should not make sibling worktrees look bare",
	);
	const worktreeConfigEnabled = runTool(
		"git",
		["config", "--get", "extensions.worktreeConfig"],
		hydrateCache,
	).stdout.trim();
	assert.equal(
		worktreeConfigEnabled,
		"true",
		"read-only hardening should enable Git worktree-local config",
	);

	const hydrateWritableRestore = run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assertOk(hydrateWritableRestore, "hydrate-repo.workspace writable restore failed");
	assert.match(
		hydrateWritableRestore.stdout,
		new RegExp(
			`^updated repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target commit=[0-9a-f]{40}$`,
			"m",
		),
	);
	const pushUrlAfterRestore = runGitUnchecked(
		["config", "--worktree", "--get", "remote.origin.pushurl"],
		join(hydrateBridge, "workspace", "hydrated-target"),
	);
	assert.notEqual(
		pushUrlAfterRestore.status,
		0,
		"worktree-local pushurl override should be removed in writable mode",
	);
	const sharedCachePushUrlAfterRestore = runGitUnchecked(
		["config", "--get", "remote.origin.pushurl"],
		hydrateCache,
	);
	assert.notEqual(
		sharedCachePushUrlAfterRestore.status,
		0,
		"writable restore should leave shared cache pushurl unset",
	);

	const releaseCommit = runTool(
		"git",
		["rev-parse", "release/candidate^{commit}"],
		cloudSourceRepo,
	).stdout.trim();
	const hydrateAtRef = run(
		["hydrate-repo.workspace", hydrateRepoId, "--at", "release/candidate"],
		hydrateBridge,
	);
	assertOk(hydrateAtRef, "hydrate-repo.workspace --at failed");
	assert.match(
		hydrateAtRef.stdout,
		new RegExp(
			`^updated repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target commit=[0-9a-f]{40}$`,
			"m",
		),
	);
	const hydratedHeadAtRef = runTool(
		"git",
		["rev-parse", "HEAD"],
		join(hydrateBridge, "workspace", "hydrated-target"),
	).stdout.trim();
	assert.equal(hydratedHeadAtRef, releaseCommit, "--at should retarget hydrated worktree commit");

	write(hydratedMarkerPath, `id: ${otherRepoId}\n`);
	const markerMismatch = run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assert.notEqual(markerMismatch.status, 0, "marker mismatch unexpectedly succeeded");
	assert.match(markerMismatch.stderr, new RegExp(`marker mismatch for repo ${hydrateRepoId}`));
	assert.equal(readFileSync(hydratedMarkerPath, "utf8"), `id: ${otherRepoId}\n`);

	write(hydratedMarkerPath, `  id: ${hydrateRepoId}\n`);
	const markerIndented = run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assert.notEqual(markerIndented.status, 0, "indented marker unexpectedly succeeded");
	assert.match(markerIndented.stderr, /invalid marker format .*no leading indentation is allowed/);

	write(hydratedMarkerPath, `id: ${hydrateRepoId}\nextra: nope\n`);
	const markerExtraKey = run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assert.notEqual(markerExtraKey.status, 0, "extra marker key unexpectedly succeeded");
	assert.match(markerExtraKey.stderr, /invalid marker format .*exactly one top-level key 'id'/);

	const missingRepo = run(["hydrate-repo.workspace", "repo-does-not-exist"], hydrateBridge);
	assert.notEqual(missingRepo.status, 0, "missing repo doc unexpectedly succeeded");
	assert.match(missingRepo.stderr, /repo not found: repo-does-not-exist/);

	const fallbackCreate = run(["hydrate-repo.workspace", fallbackRepoId], hydrateBridge);
	assertOk(fallbackCreate, "hydrate-repo.workspace fallback path failed");
	assert.equal(existsSync(join(hydrateBridge, "workspace", "fallback-target", ".git")), true);
	const fallbackCache = join(hydrateBridge, ".nosedive", "cache", fallbackRepoId);
	assert.equal(
		gitCommonDir(join(hydrateBridge, "workspace", "fallback-target")),
		realpathSync(fallbackCache),
		"local-only hydration should create the workspace worktree from the managed cache",
	);
	assert.notEqual(
		gitCommonDir(join(hydrateBridge, "workspace", "fallback-target")),
		gitCommonDir(sourceRepo),
		"local-only hydration should not create a direct worktree from meta.remotes.local",
	);

	const staleTarget = join(hydrateBridge, "workspace", "stale-target");
	const staleCache = join(hydrateBridge, ".nosedive", "cache", staleWorktreeRepoId);
	mkdirSync(dirname(staleCache), { recursive: true });
	runTool("git", ["clone", "--bare", sourceRepo, staleCache], hydrateBridge);
	runTool("git", ["worktree", "add", "--detach", staleTarget, localMainCommit], staleCache);
	assert.equal(
		existsSync(staleTarget),
		true,
		"stale fixture should create a registered worktree before deleting it",
	);
	rmSync(staleTarget, { recursive: true, force: true });
	const staleHydrate = run(["hydrate-repo.workspace", staleWorktreeRepoId], hydrateBridge);
	assertOk(
		staleHydrate,
		"hydrate-repo.workspace should prune missing registered worktree paths before create",
	);
	assert.match(
		staleHydrate.stdout,
		new RegExp(
			`^created repo=${staleWorktreeRepoId} path=workspace[\\\\/]stale-target commit=[0-9a-f]{40}$`,
			"m",
		),
	);
	assert.equal(
		gitCommonDir(staleTarget),
		realpathSync(staleCache),
		"stale registration recovery should recreate the worktree from the managed cache",
	);
	assert.equal(
		runTool("git", ["status", "--short", "--untracked-files=all"], staleTarget).stdout,
		"",
		"repo ownership marker should not dirty a worktree created after stale registration recovery",
	);

	const unresolvedTarget = join(hydrateBridge, "workspace", "unresolved-target");
	write(
		join(hydrateBridge, "kb", "repo-unresolved.md"),
		`---
kind: repo
id: ${unresolvedRepoId}
name: unresolved
gist: "Unresolved ref fixture"
meta:
  worktree-path: workspace/unresolved-target
  remotes:
    local: repos/source
---
`,
	);
	const unresolvedRef = run(
		["hydrate-repo.workspace", unresolvedRepoId, "--at", "does-not-exist"],
		hydrateBridge,
	);
	assert.notEqual(unresolvedRef.status, 0, "unresolved ref unexpectedly succeeded");
	assert.match(
		unresolvedRef.stderr,
		new RegExp(`failed to resolve ref for repo ${unresolvedRepoId}: ref=does-not-exist`),
	);
	assert.equal(
		existsSync(unresolvedTarget),
		false,
		"target path should not be created when ref resolution fails",
	);

	const emptyFailTarget = join(hydrateBridge, "workspace", "empty-fail-target");
	mkdirSync(emptyFailTarget, { recursive: true });
	write(
		join(hydrateBridge, "kb", "repo-empty-fail.md"),
		`---
kind: repo
id: ${emptyFailRepoId}
name: empty-fail
gist: "Empty target worktree failure fixture"
meta:
  worktree-path: workspace/empty-fail-target
  remotes:
    local: repos/source-empty-fail
---
`,
	);
	const emptyFailCache = join(hydrateBridge, ".nosedive", "cache", emptyFailRepoId);
	mkdirSync(dirname(emptyFailCache), { recursive: true });
	runTool("git", ["clone", "--bare", emptyFailSourceRepo, emptyFailCache], hydrateBridge);
	const cacheGitDir = runTool("git", ["rev-parse", "--git-dir"], emptyFailCache).stdout.trim();
	const cacheWorktreesPath = join(emptyFailCache, cacheGitDir, "worktrees");
	write(cacheWorktreesPath, "block worktree dir creation\n");
	const emptyDirFailure = run(["hydrate-repo.workspace", emptyFailRepoId], hydrateBridge);
	assert.notEqual(
		emptyDirFailure.status,
		0,
		"empty target worktree failure unexpectedly succeeded",
	);
	assert.match(
		emptyDirFailure.stderr,
		new RegExp(`failed to create worktree for repo ${emptyFailRepoId} at .*empty-fail-target`),
	);
	assert.equal(
		readdirSync(emptyFailTarget).length,
		0,
		"empty target directory should remain unchanged when worktree creation fails",
	);

	const unsafePath = run(["hydrate-repo.workspace", unsafeRepoId], hydrateBridge);
	assert.notEqual(unsafePath.status, 0, "unsafe target path unexpectedly succeeded");
	assert.match(unsafePath.stderr, new RegExp(`unsafe target path for repo ${unsafeRepoId}`));

	write(hydratedMarkerPath, `id: ${hydrateRepoId}\n`);
	assertOk(
		run(["hydrate-repo.workspace", hydrateRepoId, "--at", "main"], hydrateBridge),
		"restore hydrated target on main before dehydrate tests failed",
	);

	const dehydrateById = run(["dehydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assertOk(dehydrateById, "dehydrate-repo.workspace by id failed");
	assert.match(
		dehydrateById.stdout,
		new RegExp(`^removed repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target$`, "m"),
	);
	assert.equal(
		existsSync(join(hydrateBridge, "workspace", "hydrated-target")),
		false,
		"dehydrate by id should remove hydrated target",
	);
	assert.equal(
		existsSync(join(hydrateBridge, ".nosedive", "cache", hydrateRepoId)),
		true,
		"dehydrate should preserve managed cache",
	);

	assertOk(
		run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge),
		"rehydrate before dehydrate by name failed",
	);
	const dehydrateByName = run(["dehydrate-repo.workspace", "hydrate"], hydrateBridge);
	assertOk(dehydrateByName, "dehydrate-repo.workspace by name failed");
	assert.match(
		dehydrateByName.stdout,
		new RegExp(`^removed repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target$`, "m"),
	);

	assertOk(
		run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge),
		"rehydrate before dehydrate by path failed",
	);
	const dehydrateByPath = run(
		["dehydrate-repo.workspace", "workspace/hydrated-target"],
		hydrateBridge,
	);
	assertOk(dehydrateByPath, "dehydrate-repo.workspace by directory path failed");
	assert.match(
		dehydrateByPath.stdout,
		new RegExp(`^removed repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target$`, "m"),
	);

	assertOk(
		run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge),
		"rehydrate before dehydrate by marker failed",
	);
	const dehydrateByMarker = run(
		["dehydrate-repo.workspace", "workspace/hydrated-target/.nosedive-ref"],
		hydrateBridge,
	);
	assertOk(dehydrateByMarker, "dehydrate-repo.workspace by marker path failed");
	assert.match(
		dehydrateByMarker.stdout,
		new RegExp(`^removed repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target$`, "m"),
	);

	const dehydrateNoop = run(["dehydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assertOk(dehydrateNoop, "dehydrate-repo.workspace noop failed");
	assert.match(
		dehydrateNoop.stdout,
		new RegExp(`^noop repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target$`, "m"),
	);

	assertOk(
		run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge),
		"rehydrate before dirty protection check failed",
	);
	const dirtyTarget = join(hydrateBridge, "workspace", "hydrated-target");
	write(join(dirtyTarget, ".assertion-dirty"), "dirty\n");
	const dirtyWithoutForce = run(["dehydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assert.notEqual(
		dirtyWithoutForce.status,
		0,
		"dirty dehydrate without --force unexpectedly succeeded",
	);
	assert.match(dirtyWithoutForce.stderr, /(dirty|uncommitted|force)/i);
	assert.equal(
		existsSync(join(dirtyTarget, ".assertion-dirty")),
		true,
		"dirty target should remain after refusal",
	);
	const dirtyWithForce = run(["dehydrate-repo.workspace", hydrateRepoId, "--force"], hydrateBridge);
	assertOk(dirtyWithForce, "dirty dehydrate with --force failed");
	assert.match(
		dirtyWithForce.stdout,
		new RegExp(`^removed repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target$`, "m"),
	);

	assertOk(
		run(["hydrate-repo.workspace", hydrateRepoId], hydrateBridge),
		"rehydrate before unpublished-commit protection check failed",
	);
	const aheadTarget = join(hydrateBridge, "workspace", "hydrated-target");
	write(join(aheadTarget, ".assertion-ahead"), "ahead\n");
	runTool("git", ["add", ".assertion-ahead"], aheadTarget);
	runTool(
		"git",
		[
			"-c",
			"user.name=Nosedive Assertion",
			"-c",
			"user.email=assertion@example.invalid",
			"commit",
			"-m",
			"assertion unpublished commit",
		],
		aheadTarget,
	);
	const aheadWithoutForce = run(["dehydrate-repo.workspace", hydrateRepoId], hydrateBridge);
	assert.notEqual(
		aheadWithoutForce.status,
		0,
		"ahead dehydrate without --force unexpectedly succeeded",
	);
	assert.match(aheadWithoutForce.stderr, /(unpublished|unpushed|ahead|force)/i);
	assert.equal(
		existsSync(join(aheadTarget, ".assertion-ahead")),
		true,
		"ahead target should remain after refusal",
	);
	const aheadWithForce = run(["dehydrate-repo.workspace", hydrateRepoId, "--force"], hydrateBridge);
	assertOk(aheadWithForce, "ahead dehydrate with --force failed");
	assert.match(
		aheadWithForce.stdout,
		new RegExp(`^removed repo=${hydrateRepoId} path=workspace[\\\\/]hydrated-target$`, "m"),
	);

	const outsideDehydrateDir = join(tmp, "outside-dehydrate-target");
	mkdirSync(outsideDehydrateDir, { recursive: true });
	write(join(outsideDehydrateDir, "keep.txt"), "outside\n");
	const insideUnowned = join(hydrateBridge, "workspace", "not-owned");
	mkdirSync(insideUnowned, { recursive: true });
	write(join(insideUnowned, "keep.txt"), "inside\n");

	const unsafeOutside = run(
		["dehydrate-repo.workspace", "../outside-dehydrate-target"],
		hydrateBridge,
	);
	assert.notEqual(unsafeOutside.status, 0, "outside-workspace dehydrate unexpectedly succeeded");
	assert.match(unsafeOutside.stderr, /(workspace|outside|relative)/i);

	const unsafeInside = run(["dehydrate-repo.workspace", "workspace/not-owned"], hydrateBridge);
	assert.notEqual(unsafeInside.status, 0, "unowned in-workspace dehydrate unexpectedly succeeded");
	assert.match(unsafeInside.stderr, /(marker|\.nosedive-ref|owned)/i);

	const unsafeOutsideForce = run(
		["dehydrate-repo.workspace", "../outside-dehydrate-target", "--force"],
		hydrateBridge,
	);
	assert.notEqual(
		unsafeOutsideForce.status,
		0,
		"outside-workspace dehydrate with --force unexpectedly succeeded",
	);

	const unsafeInsideForce = run(
		["dehydrate-repo.workspace", "workspace/not-owned", "--force"],
		hydrateBridge,
	);
	assert.notEqual(
		unsafeInsideForce.status,
		0,
		"unowned in-workspace dehydrate with --force unexpectedly succeeded",
	);

	assert.equal(
		readFileSync(join(outsideDehydrateDir, "keep.txt"), "utf8"),
		"outside\n",
		"outside-workspace file should remain untouched",
	);
	assert.equal(
		readFileSync(join(insideUnowned, "keep.txt"), "utf8"),
		"inside\n",
		"in-workspace unowned file should remain untouched",
	);

	write(
		join(bridge, "kb", "bad.md"),
		`---
kind: convention
id: bad-doc
name: bad
gist: "unterminated
---
`,
	);

	const invalid = run(["apply", "--dry-run"], bridge);
	assert.notEqual(invalid.status, 0, "invalid YAML unexpectedly succeeded");
	assert.match(invalid.stderr, /invalid YAML in frontmatter in .*bad\.md/);
	rmSync(join(bridge, "kb", "bad.md"), { force: true });

	write(
		join(bridge, "kb", "legacy-scope.md"),
		`---
kind: convention
id: legacy-scope
name: legacy-scope
gist: "Legacy shorthand scopes are rejected after hard cut."
scopes:
  - repo-writable/app:gist
---

# Legacy scope
`,
	);

	const legacyScope = run(["apply", "--dry-run"], bridge);
	assert.notEqual(legacyScope.status, 0, "legacy scope shorthand unexpectedly succeeded");
	assert.match(
		legacyScope.stderr,
		/legacy scope shorthand is not supported in .*legacy-scope\.md scopes\[0\]/,
	);
	rmSync(join(bridge, "kb", "legacy-scope.md"), { force: true });

	write(
		join(bridge, "backlog", "yaml-frontmatter", "YamlFrontmatter.md"),
		`---
phase: building
gist: "Exercise valid YAML: quoted effort gist"
repos:
  - repo-writable:rw
---

# YAML frontmatter

Build the YAML-aware workspace work order.
`,
	);

	const staleEffortRepoFlag = run(["apply", "--dry-run"], bridge);
	assertOk(
		staleEffortRepoFlag,
		"apply should use the active dive scopes, not stale current effort repos",
	);
	assert.match(staleEffortRepoFlag.stdout, /Dive:      active-dive/);
	assert.match(
		staleEffortRepoFlag.stdout,
		/writable\s+workspace\/writable \(repo-writable, base develop\)/,
	);

	const initHelp = run(["init", "--help"], root);
	assertOk(initHelp, "init --help failed");
	assert.match(initHelp.stdout, /Usage: nosedive init \[--headless\]/);
	assert.match(initHelp.stdout, /--headless skips prompts/);

	const unknownInitOption = run(["init", "--bogus"], root, "");
	assert.notEqual(unknownInitOption.status, 0, "init with unknown option unexpectedly succeeded");
	assert.match(unknownInitOption.stderr, /unknown init option: --bogus/);

	const initBridge = join(tmp, "init-bridge");
	mkdirSync(initBridge, { recursive: true });
	runTool("git", ["init", "-b", "main"], initBridge);
	runTool("git", ["config", "user.name", "Init Person"], initBridge);
	runTool("git", ["config", "user.email", "init@example.invalid"], initBridge);

	const initFresh = run(["init"], initBridge, "\n\n\n\n\n\n\n\n");
	assertOk(initFresh, "init on empty directory failed");
	assert.match(initFresh.stdout, /Wrote \.nosediverc/);
	assert.match(
		initFresh.stdout,
		new RegExp(`Seeded ${packageFoundationDocCount} foundation docs into \\.\\/kb`),
	);
	const freshRc = readFileSync(join(initBridge, ".nosediverc"), "utf8");
	assert.equal(
		freshRc,
		[
			"workspace: ./workspace",
			"backlog: ./backlog",
			"kb: ./kb",
			"home-branch: main",
			"work-branch-prefix: work/",
			"pilot-name: Init Person",
			"pilot-email: init@example.invalid",
			"agents:",
			"  - copilot",
			"",
		].join("\n"),
	);
	for (const packageFoundationDoc of packageFoundationDocs) {
		assert.equal(existsSync(join(initBridge, "kb", packageFoundationDoc)), true);
	}
	assert.equal(existsSync(join(initBridge, "kb", packageNonFoundationDoc)), false);
	assert.equal(existsSync(join(initBridge, ".gitignore")), false);
	const initExclude = readFileSync(join(initBridge, ".git", "info", "exclude"), "utf8");
	assert.match(initExclude, /# BEGIN nosedive-managed package-foundation exclude/);
	assert.match(initExclude, /^\.nosediverc$/m);
	for (const packageFoundationDoc of packageFoundationDocs) {
		assert.match(initExclude, new RegExp(`^kb/${packageFoundationDoc}$`, "m"));
	}
	assert.match(initExclude, /# END nosedive-managed package-foundation exclude/);
	assert.doesNotMatch(initExclude, new RegExp(`^kb/${packageNonFoundationDoc}$`, "m"));
	const initGitStatus = runTool(
		"git",
		["status", "--ignored", "--short", "--untracked-files=all"],
		initBridge,
	).stdout;
	assert.match(initGitStatus, /^!! \.nosediverc$/m);
	for (const packageFoundationDoc of packageFoundationDocs) {
		assert.match(initGitStatus, new RegExp(`!! kb/${packageFoundationDoc}`));
	}
	assert.doesNotMatch(initGitStatus, /\.gitignore/);

	const initReprompt = run(["init"], initBridge, "\n\n\n\n\n\n\nbogus\ncopilot,claude\n");
	assertOk(initReprompt, "init re-run with invalid agent failed");
	assert.match(initReprompt.stderr, /unknown agent\(s\): bogus \(options: copilot, claude\)/);
	const repromptedRc = readFileSync(join(initBridge, ".nosediverc"), "utf8");
	assert.match(repromptedRc, /workspace: \.\/workspace/);
	assert.match(repromptedRc, /agents:\n  - copilot\n  - claude\n$/);

	const headlessFreshBridge = join(tmp, "headless-fresh-bridge");
	mkdirSync(headlessFreshBridge, { recursive: true });
	runTool("git", ["init", "-b", "main"], headlessFreshBridge);
	runTool("git", ["config", "user.name", "Headless Person"], headlessFreshBridge);
	runTool("git", ["config", "user.email", "headless@example.invalid"], headlessFreshBridge);

	const initHeadlessFresh = run(["init", "--headless"], headlessFreshBridge, "");
	assertOk(initHeadlessFresh, "headless init on empty directory failed");
	assert.doesNotMatch(initHeadlessFresh.stdout, /workspace \[/);
	assert.doesNotMatch(initHeadlessFresh.stdout, /agents, comma-separated/);
	assert.match(initHeadlessFresh.stdout, /Wrote \.nosediverc/);
	assert.match(
		initHeadlessFresh.stdout,
		new RegExp(`Seeded ${packageFoundationDocCount} foundation docs into \\.\\/kb`),
	);
	assert.equal(
		readFileSync(join(headlessFreshBridge, ".nosediverc"), "utf8"),
		[
			"workspace: ./workspace",
			"backlog: ./backlog",
			"kb: ./kb",
			"home-branch: main",
			"work-branch-prefix: work/",
			"pilot-name: Headless Person",
			"pilot-email: headless@example.invalid",
			"agents:",
			"  - copilot",
			"",
		].join("\n"),
	);
	for (const packageFoundationDoc of packageFoundationDocs) {
		assert.equal(existsSync(join(headlessFreshBridge, "kb", packageFoundationDoc)), true);
	}
	const headlessFreshExclude = readFileSync(
		join(headlessFreshBridge, ".git", "info", "exclude"),
		"utf8",
	);
	assert.match(headlessFreshExclude, /^\.nosediverc$/m);
	for (const packageFoundationDoc of packageFoundationDocs) {
		assert.match(headlessFreshExclude, new RegExp(`^kb/${packageFoundationDoc}$`, "m"));
	}

	const headlessExistingBridge = join(tmp, "headless-existing-bridge");
	mkdirSync(headlessExistingBridge, { recursive: true });
	runTool("git", ["init", "-b", "main"], headlessExistingBridge);
	runTool("git", ["config", "user.name", "Detected Name"], headlessExistingBridge);
	runTool("git", ["config", "user.email", "detected@example.invalid"], headlessExistingBridge);
	write(
		join(headlessExistingBridge, ".nosediverc"),
		`workspace: ./custom-workspace
kb: ./custom-kb
pilot-name: Existing Pilot
agents:
  - claude
`,
	);

	const initHeadlessExisting = run(["init", "--headless"], headlessExistingBridge, "");
	assertOk(initHeadlessExisting, "headless init with existing config failed");
	assert.doesNotMatch(initHeadlessExisting.stdout, /workspace \[/);
	assert.doesNotMatch(initHeadlessExisting.stdout, /agents, comma-separated/);
	assert.match(
		initHeadlessExisting.stdout,
		new RegExp(`Seeded ${packageFoundationDocCount} foundation docs into \\.\\/custom-kb`),
	);
	assert.equal(
		readFileSync(join(headlessExistingBridge, ".nosediverc"), "utf8"),
		[
			"workspace: ./custom-workspace",
			"backlog: ./backlog",
			"kb: ./custom-kb",
			"home-branch: main",
			"work-branch-prefix: work/",
			"pilot-name: Existing Pilot",
			"pilot-email: detected@example.invalid",
			"agents:",
			"  - claude",
			"",
		].join("\n"),
	);
	for (const packageFoundationDoc of packageFoundationDocs) {
		assert.equal(existsSync(join(headlessExistingBridge, "custom-kb", packageFoundationDoc)), true);
	}
	const headlessExistingExclude = readFileSync(
		join(headlessExistingBridge, ".git", "info", "exclude"),
		"utf8",
	);
	assert.match(headlessExistingExclude, /^\.nosediverc$/m);
	for (const packageFoundationDoc of packageFoundationDocs) {
		assert.match(headlessExistingExclude, new RegExp(`^custom-kb/${packageFoundationDoc}$`, "m"));
	}

	const nonGitInit = join(tmp, "non-git-init");
	mkdirSync(nonGitInit, { recursive: true });
	const initOutsideGit = run(["init"], nonGitInit, "");
	assert.notEqual(initOutsideGit.status, 0, "init outside git unexpectedly succeeded");
	assert.match(initOutsideGit.stderr, /nosedive init must be run inside a git repository/);
} finally {
	rmSync(tmp, { recursive: true, force: true });
}
